### ISSUE TITLE
Recursion limit exceeded for higher kinded GADT involving Id

### ISSUE THREAD

**Issue by Katrix** [scala/scala3#10946]
## Minimized code

```Scala
enum Amount[F[_]]:
  case ZeroOrOne  extends Amount[Option]
  case ExactlyOne extends Amount[[A] =>> A]
  case OneOrMore  extends Amount[Seq]
```

## Output

```scala
Recursion limit exceeded.
Maybe there is an illegal cyclic reference?
If that's not the case, you could also try to increase the stacksize using the -Xss JVM option.
A recurring operation is (inner to outer):

  subtype [X0] >: Option[X0] & X0 <: Option[X0] | X0 <:< Seq
```

## Expectation
It compiles. Rewriting it to a sealed trait works fine.

**Comment by yzia2000** [comment]
This fails too:
```scala
trait Foo1[A]
trait Foo2[A]
trait Foo3[A]

enum Amount[F[_]]:
  case ZeroOrOne  extends Amount[Foo1]
  case ExactlyOne extends Amount[Foo2]
  case OneOrMore  extends Amount[Foo3]
```

I tried running with a -Xss set to 1g and it takes a very long time but approaches Recursion limit as well.

**Comment by yzia2000** [comment]
For those interested in stack trace:
```scala
trait Foo1[A]
trait Foo2[A]
trait Foo3[A]

enum Bar[F[_]]:
  case Bar1  extends Bar[Foo1]
  case Bar2 extends Bar[Foo2]
  case Bar3 extends Bar[Foo3]
```

```
assertion failedmpiler / Test / testOnly 1s
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
        at dotty.tools.dotc.core.TypeComparer.monitoredIsSubType$1(TypeComparer.scala:247)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.compareTypeLambda$1(TypeComparer.scala:722)
        at dotty.tools.dotc.core.TypeComparer.thirdTry$1(TypeComparer.scala:730)
        at dotty.tools.dotc.core.TypeComparer.secondTry$1(TypeComparer.scala:538)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:398)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1457)
        at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:208)
        at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:218)
        at dotty.tools.dotc.core.TypeComparer.isSameType(TypeComparer.scala:2162)
        at dotty.tools.dotc.core.TypeComparer.isSame(TypeComparer.scala:2169)
        at dotty.tools.dotc.core.ConstraintHandling.op$proxy4$1(ConstraintHandling.scala:464)
        at dotty.tools.dotc.core.ConstraintHandling.isSameTypeWhenFrozen(ConstraintHandling.scala:464)
        at dotty.tools.dotc.core.ConstraintHandling.isSameTypeWhenFrozen$(ConstraintHandling.scala:29)
        at dotty.tools.dotc.core.TypeComparer.isSameTypeWhenFrozen(TypeComparer.scala:30)
        at dotty.tools.dotc.core.TypeComparer.singletonInterval(TypeComparer.scala:2203)
        at dotty.tools.dotc.core.TypeComparer.lubArgs(TypeComparer.scala:2304)
        at dotty.tools.dotc.core.TypeComparer$.lubArgs(TypeComparer.scala:2965)
        at dotty.tools.dotc.core.TypeOps$.mergeRefinedOrApplied$1(TypeOps.scala:272)
        at dotty.tools.dotc.core.TypeOps$.orDominator(TypeOps.scala:393)
        at dotty.tools.dotc.core.Types$OrType.join(Types.scala:3407)
        at dotty.tools.dotc.core.Types$OrType.widenUnionWithoutNull(Types.scala:3423)
        at dotty.tools.dotc.core.Types$Type.widenUnion(Types.scala:1294)
        at dotty.tools.dotc.core.ConstraintHandling.widenOr$1(ConstraintHandling.scala:652)
        at dotty.tools.dotc.core.ConstraintHandling.widenInferred(ConstraintHandling.scala:668)
        at dotty.tools.dotc.core.ConstraintHandling.widenInferred$(ConstraintHandling.scala:29)
        at dotty.tools.dotc.core.TypeComparer.widenInferred(TypeComparer.scala:30)
        at dotty.tools.dotc.core.TypeComparer$.widenInferred(TypeComparer.scala:3016)
        at dotty.tools.dotc.typer.Namer.rhsType$1(Namer.scala:1892)
        at dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:1898)
        at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1899)
        at dotty.tools.dotc.typer.Namer.inferredResultType(Namer.scala:1910)
        at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1657)
        at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1664)
        at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1755)
        at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:787)
        at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:922)
        at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:810)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:174)
        at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:187)
        at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:189)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:390)
        at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2891)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2916)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3012)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3080)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3084)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3106)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3152)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2584)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2938)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2942)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3012)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3080)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3084)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3106)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3152)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2714)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2983)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3013)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3080)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3084)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3196)
        at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:44)
        at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$adapted$1(TyperPhase.scala:54)
        at scala.Function0.apply$mcV$sp(Function0.scala:42)
        at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:437)
        at dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:54)
        at dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$3(TyperPhase.scala:88)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:88)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:247)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:263)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:271)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:280)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:280)
        at dotty.tools.dotc.Run.compileSources(Run.scala:195)
        at dotty.tools.dotc.Run.compile(Run.scala:179)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
        at dotty.tools.dotc.Driver.process(Driver.scala:195)
        at dotty.tools.dotc.Driver.process(Driver.scala:163)
        at dotty.tools.vulpix.ParallelTesting$Test.compile(ParallelTesting.scala:533)
        at dotty.tools.vulpix.ParallelTesting$CompilationLogic.compileTestSource$$anonfun$1(ParallelTesting.scala:230)
        at scala.util.Try$.apply(Try.scala:210)

```

**Comment by yzia2000** [comment]
Hmm is the issue with the Eta expansion? Shouldn't it be like this:
```
==> isSubType [X0] >: Foo1[X0] & Foo2[X0] <: Foo1[X0] | Foo2[X0] <:< Foo3?
   ==> isSubType [X0] =>> Foo1[X0] & Foo2[X0] <:< Foo3?
```

**Comment by yzia2000** [comment]
@dwijnand can you help tell me whether the expected eta expansion is correct?

**Comment by dwijnand** [comment]
I don't recognise that as "eta-expansion" and I can't tell you if it's correct.  But I agree with you that it seems reasonable.  You could look as to why that step is taken in `Bar[Foo3] <:< Bar[?[X0] ...` but not when it's not nested.

**Comment by SethTisue** [comment]
compiles as of Scala 3.3.5
