### ISSUE TITLE
-YCheck:typer fail on dependent method derived from type parameter

### ISSUE THREAD

**Issue by bishabosha** [scala/scala3#11700]
a method with a path dependent parameter deriving from a type parameter will fail `-Ycheck:typer`

## Compiler version

3.0.0-RC1

## Minimized code

```Scala
class Context {
  type Type
}

def foo[Ctx <: Context](using ctx: Ctx)(tpe: ctx.Type): ctx.Type = tpe

@main def Test =

  given Context with {
    type Type = String
  }

  val t1: String = foo("hello")
```

## Output (click arrow to expand)
<details>

```scala
*** error while checking tests/run/i11583.scala after phase typer ***
exception occurred while compiling tests/run/i11583.scala
java.lang.AssertionError: assertion failed: Types differ
Original type : (using ctx: given_Context.type)(tpe: ctx.Type): ctx.Type
After checking: (using ctx: given_Context.type)(tpe: String): String
Original tree : foo[given_Context.type]
After checking: foo[given_Context.type]
Why different :
             Subtype trace:
  ==> (using ctx: given_Context.type)(tpe: String): String <:< (using ctx: given_Context.type)(tpe: ctx.Type): ctx.Type  
    ==> (using ctx: given_Context.type)(tpe: String): String <:< (using ctx: given_Context.type)(tpe: ctx.Type): ctx.Type recur 
    <== (using ctx: given_Context.type)(tpe: String): String <:< (using ctx: given_Context.type)(tpe: ctx.Type): ctx.Type recur  = false
  <== (using ctx: given_Context.type)(tpe: String): String <:< (using ctx: given_Context.type)(tpe: ctx.Type): ctx.Type   = false while compiling tests/run/i11583.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Types differ
Original type : (using ctx: given_Context.type)(tpe: ctx.Type): ctx.Type
After checking: (using ctx: given_Context.type)(tpe: String): String
Original tree : foo[given_Context.type]
After checking: foo[given_Context.type]
Why different :
             Subtype trace:
  ==> (using ctx: given_Context.type)(tpe: String): String <:< (using ctx: given_Context.type)(tpe: ctx.Type): ctx.Type  
    ==> (using ctx: given_Context.type)(tpe: String): String <:< (using ctx: given_Context.type)(tpe: ctx.Type): ctx.Type recur 
    <== (using ctx: given_Context.type)(tpe: String): String <:< (using ctx: given_Context.type)(tpe: ctx.Type): ctx.Type recur  = false
  <== (using ctx: given_Context.type)(tpe: String): String <:< (using ctx: given_Context.type)(tpe: ctx.Type): ctx.Type   = false
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:346)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:317)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:834)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:987)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:301)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:102)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2593)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2655)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:333)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:317)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:834)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:987)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:301)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:102)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2593)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2655)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:333)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:317)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
	at dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:2023)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2567)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2654)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:333)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:317)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2746)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2796)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:533)
	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:969)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:973)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$2$$anonfun$1(TreeChecker.scala:515)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:199)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1(TreeChecker.scala:515)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withBlock(TreeChecker.scala:227)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock(TreeChecker.scala:515)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2601)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2655)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:333)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:317)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
	at dotty.tools.dotc.typer.Typer.$anonfun$35(Typer.scala:2080)
	at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:223)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2080)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef$$anonfun$1(TreeChecker.scala:490)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:199)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef(TreeChecker.scala:493)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2570)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2654)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:333)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:317)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2746)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2796)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:533)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2226)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedClassDef(TreeChecker.scala:468)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2581)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2585)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2654)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:333)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:317)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2746)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2796)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:533)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2378)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedPackageDef(TreeChecker.scala:559)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2626)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2655)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:333)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:317)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
	at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:151)
	at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:120)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
	at dotty.tools.dotc.Run.compile(Run.scala:150)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.dotc.Driver.process(Driver.scala:186)
	at dotty.tools.dotc.Driver.process(Driver.scala:155)
	at dotty.tools.dotc.Driver.process(Driver.scala:167)
	at dotty.tools.dotc.Driver.main(Driver.scala:194)
	at dotty.tools.dotc.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
```
</details>

**Comment by odersky** [comment]
A crash label should be used when this is a user-facing crash. Not a failure of an internal check run.

**Comment by SolalPirelli** [comment]
No ycheck failure on main, closing
