### ISSUE TITLE
JLine error when attempting to run the REPL with piped input

### ISSUE THREAD

**Issue by deanwampler** [scala/scala3#11978]
Scala 3.0.0-RC2. A command like the following:

```shell
$ scala <<EOF
:load somestuff.scala
EOF
```

or trying:

```shell
$ echo ":load src/script/scala/progscala3/hierarchy/Asserts.scala" | scala
```

Both cause this exception:

```
Exception in thread "main" java.lang.IllegalStateException: Unable to create a system terminal
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:323)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:265)
	at dotty.tools.repl.JLineTerminal.<init>(JLineTerminal.scala:23)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:123)
	at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:114)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```

This is fairly well known issue, see for example https://youtrack.jetbrains.com/issue/IDEA-183619. I attempted to use the recommended fix, setting the property `-Dorg.jline.terminal.dumb=true`. I did this by passing the argument `-J-Dorg.jline.terminal.dumb=true` to the REPL, even though this argument is not documented for the REPL in the `-help` output. It appeared to be ignored or do nothing. I also tried setting the environment variable `JAVA_OPTS=-Dorg.jline.terminal.dumb=true` before starting the REPL, but that didn't work either. Finally, I even tried setting the property inside the REPL, i.e.,

```shell
$ scala <<EOF
System.setProperty("...", "...")
:load somestuff.scala
EOF
```

I would expect this to be too late. It also doesn't help.

Note that in the Scala 2.13 REPL, without setting the property, you get a warning that it will default to a dumb terminal, but otherwise appears to work fine.

**Comment by griggt** [comment]
These incantations seem to work (at least on Linux)

> ```shell
> $ TERM=dumb scala <<EOF
> :load somestuff.scala
> EOF
> ```

> ```shell
> $ echo ":load src/script/scala/progscala3/hierarchy/Asserts.scala" | TERM=dumb scala
> ```

But we should probably gracefully fall back to a dumb terminal like Scala 2 does, as was also [suggested here](https://github.com/lampepfl/dotty/pull/11707#issuecomment-799360461).

**Comment by deanwampler** [comment]
I just noticed in https://github.com/lampepfl/dotty/pull/11707 that using `TERM=dumb` should work. I confirmed it works on MacOS, too, just now. Thanks!

**Comment by catap** [comment]
Interesting that without `TERM=dumb` it simple doesn't work on OpenBSD

**Comment by catap** [comment]
https://github.com/scala/scala3/pull/19744 may fixe this

**Comment by Gedochao** [comment]
Sadly, this is still broken, even on the new `scala` runner / Scala CLI.

```bash
echo 'object Example { def smth = "smth" }' |scala-cli repl _   
# Compiling project (Scala 3.4.2, JVM (17))
# Compiled project (Scala 3.4.2, JVM (17))
# Exception in thread "main" java.lang.IllegalStateException: Unable to create a terminal
# 	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:394)
# 	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:362)
# 	at dotty.tools.repl.JLineTerminal.<init>(JLineTerminal.scala:25)
# 	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:145)
# 	at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:136)
# 	at dotty.tools.repl.Main$.main(Main.scala:7)
# 	at dotty.tools.repl.Main.main(Main.scala)
# 	Suppressed: java.io.IOException: Unable to find terminal provider ffm
# 		at org.jline.terminal.spi.TerminalProvider.load(TerminalProvider.java:74)
# 		at org.jline.terminal.TerminalBuilder.checkProvider(TerminalBuilder.java:667)
# 		at org.jline.terminal.TerminalBuilder.getProviders(TerminalBuilder.java:632)
# 		at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:395)
# 		... 6 more
# 	Suppressed: java.io.IOException: Unable to find terminal provider jni
# 		at org.jline.terminal.spi.TerminalProvider.load(TerminalProvider.java:74)
# 		at org.jline.terminal.TerminalBuilder.checkProvider(TerminalBuilder.java:667)
# 		at org.jline.terminal.TerminalBuilder.getProviders(TerminalBuilder.java:634)
# 		at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:395)
# 		... 6 more
# 	Suppressed: java.io.IOException: Unable to find terminal provider jansi
# 		at org.jline.terminal.spi.TerminalProvider.load(TerminalProvider.java:74)
# 		at org.jline.terminal.TerminalBuilder.checkProvider(TerminalBuilder.java:667)
# 		at org.jline.terminal.TerminalBuilder.getProviders(TerminalBuilder.java:636)
# 		at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:395)
# 		... 6 more
# 	Suppressed: java.io.IOException: Unable to load terminal provider jna: null
# 		at org.jline.terminal.spi.TerminalProvider.load(TerminalProvider.java:71)
# 		at org.jline.terminal.TerminalBuilder.checkProvider(TerminalBuilder.java:667)
# 		at org.jline.terminal.TerminalBuilder.getProviders(TerminalBuilder.java:638)
# 		at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:395)
# 		... 6 more
# 	Caused by: java.lang.reflect.InvocationTargetException
# 		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
# 		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
# 		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
# 		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
# 		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
# 		at org.jline.terminal.spi.TerminalProvider.load(TerminalProvider.java:69)
# 		... 9 more
# 	Caused by: java.lang.UnsupportedOperationException: Unsupported platform mac-aarch64
# 		at org.jline.terminal.impl.jna.JnaNativePty.isatty(JnaNativePty.java:194)
# 		at org.jline.terminal.impl.jna.JnaNativePty.isPosixSystemStream(JnaNativePty.java:170)
# 		at org.jline.terminal.impl.jna.JnaTerminalProvider.checkSystemStream(JnaTerminalProvider.java:124)
# 		at org.jline.terminal.impl.jna.JnaTerminalProvider.<init>(JnaTerminalProvider.java:31)
# 		... 15 more
```

**Comment by mbovel** [comment]
Reading https://github.com/scala/scala3/pull/11707 it seems to me that the right thing to do here might just be to keep the default value of `dump` to `null` instead of setting it to `false` when the dump terminal is not forced. This would allow JLine to fall back to a dump terminal if needed.
