### ISSUE TITLE
Passing an instance of a value class to a method accessed structurally via reflection

### ISSUE THREAD

**Issue by prolativ** [scala/scala3#16995]
## Compiler version

3.3.1-RC1-bin-20230221-847eccc-NIGHTLY and before

## Minimized code

```scala
class Foo(val i: Int) extends AnyVal
class Reflective extends reflect.Selectable

@main def run() =
  val reflective = new Reflective {
    def bar(foo: Foo) = foo.i
  }
  val i = reflective.bar(Foo(1))
```

## Output

```scala
Exception in thread "main" java.lang.NoSuchMethodException: Reflect$package$$anon$1.bar(Foo)
        at java.lang.Class.getMethod(Class.java:1786)
        at scala.reflect.Selectable.applyDynamic(Selectable.scala:38)
        at scala.reflect.Selectable.applyDynamic$(Selectable.scala:11)
        at Reflective.applyDynamic(Reflect.scala:2)
        at Reflect$package$.run(Reflect.scala:8)
        at run.main(Reflect.scala:4)
```

## Expectation

No exception should be thrown.

This is related to https://github.com/lampepfl/dotty/issues/14340 (with fix available here https://github.com/lampepfl/dotty/pull/16286) but the problem here is in the parameters of methods rather than in returned values

**Comment by prolativ** [comment]
@G1ng3r you might be interested in that

**Comment by G1ng3r** [comment]
Thanks! Will take a look into this
