### ISSUE TITLE
Illegal MatchType Error reaches the backend 

### ISSUE THREAD

**Issue by odersky** [scala/scala3#19434]
## Compiler version

3.4.0

## Minimized example

```Scala
object Test:

  object Named:
    opaque type Named[name <: String & Singleton, A] >: A = A

  type DropNames[T <: Tuple] = T match
    case Named.Named[_, x] *: xs => x *: DropNames[xs]
    case _ => T

  def f[T <: Tuple]: DropNames[T] = ???
```

## Output

```scala
an unexpected type representation reached the compiler backend while compiling named-tuples-strawman.scala: dotty.tools.dotc.core.Types$PreviousErrorType@2d9dff65. If possible, please file a bug on https://github.com/lampepfl/dotty/issues
scala.MatchError: dotty.tools.dotc.core.Types$PreviousErrorType@2d9dff65 (of class dotty.tools.dotc.core.Types$PreviousErrorType)
	at dotty.tools.backend.jvm.BCodeHelpers.dotty$tools$backend$jvm$BCodeHelpers$$typeToTypeKind(BCodeHelpers.scala:764)
	at dotty.tools.backend.jvm.BCodeHelpers$BCInnerClassGen.toTypeKind(BCodeHelpers.scala:202)
	at dotty.tools.backend.jvm.BCodeHelpers$BCInnerClassGen.toTypeKind$(BCodeHelpers.scala:130)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.toTypeKind(BCodeSkelBuilder.scala:134)
	at dotty.tools.backend.jvm.BCodeHelpers$BCInnerClassGen.asmMethodType(BCodeHelpers.scala:188)
	at dotty.tools.backend.jvm.BCodeHelpers$BCInnerClassGen.asmMethodType$(BCodeHelpers.scala:130)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.asmMethodType(BCodeSkelBuilder.scala:134)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:815)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:693)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen$$anonfun$1(BCodeSkelBuilder.scala:699)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:699)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:293)
	at dotty.tools.backend.jvm.CodeGen.genClass(CodeGen.scala:154)
	at dotty.tools.backend.jvm.CodeGen.genClassDef$1(CodeGen.scala:62)
	at dotty.tools.backend.jvm.CodeGen.genClassDefs$1(CodeGen.scala:117)
	at dotty.tools.backend.jvm.CodeGen.genClassDefs$1$$anonfun$1(CodeGen.scala:115)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.CodeGen.genClassDefs$1(CodeGen.scala:115)
	at dotty.tools.backend.jvm.CodeGen.genUnit(CodeGen.scala:120)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:83)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:354)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:360)
	at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:91)
	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:315)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:337)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:348)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:357)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:357)
	at dotty.tools.dotc.Run.compileSources(Run.scala:261)
	at dotty.tools.dotc.Run.compile(Run.scala:246)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
	at dotty.tools.dotc.Driver.process(Driver.scala:197)
	at dotty.tools.dotc.Driver.process(Driver.scala:165)
	at dotty.tools.dotc.Driver.process(Driver.scala:177)
	at dotty.tools.dotc.Driver.main(Driver.scala:207)
	at dotty.tools.dotc.Main.main(Main.scala)
Error while emitting named-tuples-strawman.scala
dotty.tools.dotc.core.Types$PreviousErrorType@2d9dff65 (of class dotty.tools.dotc.core.Types$PreviousErrorType)
1 warning found
1 error found
```

## Expectation

A regular error, like this one:
```
1 |object Test:
  |       ^
  |       The match type contains an illegal case:
  |           case Test.Named.Named[_, x] *: xs => x *: Test.DropNames[xs]
  |       (this error can be ignored for now with `-source:3.3`)
```
I verified that that was the error that generated the illegal error type.

**Comment by odersky** [comment]
Also, I am not sure why this program would be illegal. I guess it should not be.

The problem seems to be that the match type is reduced only at erasure. At that time, opaque types are already eliminated, so `Named` looks like a normal type alias. So the type comparer complains.

**Comment by odersky** [comment]
Here's the stacktrace I see when I add a `new Error().printStackTrace()` to line 3573 of TypeComparer where the ErrorType gets generated:
```
	at dotty.tools.dotc.core.TrackingTypeComparer.recur$2(TypeComparer.scala:3574)
	at dotty.tools.dotc.core.TrackingTypeComparer.op$proxy82$1(TypeComparer.scala:3614)
	at dotty.tools.dotc.core.TrackingTypeComparer.matchCases(TypeComparer.scala:3615)
	at dotty.tools.dotc.core.Types$MatchType.matchCases$1(Types.scala:5041)
	at dotty.tools.dotc.core.Types$MatchType.reduced$$anonfun$1(Types.scala:5050)
	at dotty.tools.dotc.core.TypeComparer.inSubComparer(TypeComparer.scala:3054)
	at dotty.tools.dotc.core.TypeComparer.tracked(TypeComparer.scala:3064)
	at dotty.tools.dotc.core.TypeComparer$.tracked(TypeComparer.scala:3232)
	at dotty.tools.dotc.core.Types$MatchType.reduced(Types.scala:5050)
	at dotty.tools.dotc.core.Types$MatchType.tryNormalize(Types.scala:4999)
	at dotty.tools.dotc.core.Types$AppliedType.tryMatchAlias$1$$anonfun$1(Types.scala:4562)
	at dotty.tools.dotc.core.MatchTypeTrace$.recurseWith(MatchTypeTrace.scala:81)
	at dotty.tools.dotc.core.Types$AppliedType.tryMatchAlias$1(Types.scala:4563)
	at dotty.tools.dotc.core.Types$AppliedType.tryNormalize(Types.scala:4568)
	at dotty.tools.dotc.core.Types$AppliedType.translucentSuperType(Types.scala:4541)
	at dotty.tools.dotc.core.TypeErasure.checkedSuperType(TypeErasure.scala:752)
	at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$apply(TypeErasure.scala:642)
	at dotty.tools.dotc.core.TypeErasure.eraseResult(TypeErasure.scala:879)
	at dotty.tools.dotc.core.TypeErasure.eraseInfo(TypeErasure.scala:815)
	at dotty.tools.dotc.core.TypeErasure$.transformInfo(TypeErasure.scala:273)
	at dotty.tools.dotc.transform.Erasure.transform(Erasure.scala:96)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.goForward$1(Denotations.scala:831)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:877)
	at dotty.tools.dotc.core.Symbols$Symbol.recomputeDenot(Symbols.scala:124)
	at dotty.tools.dotc.core.Symbols$Symbol.computeDenot(Symbols.scala:118)
	at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:111)
	at dotty.tools.dotc.core.Symbols$.toDenot(Symbols.scala:520)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.paramAccessors$$anonfun$1(SymDenotations.scala:2386)
	at dotty.tools.dotc.core.Scopes$Scope.filter(Scopes.scala:103)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.paramAccessors(SymDenotations.scala:2386)
	at dotty.tools.dotc.core.Contexts$Context.superCallContext(Contexts.scala:417)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2720)
	at dotty.tools.dotc.transform.Erasure$Typer.typedClassDef(Erasure.scala:1047)
```

**Comment by sjrd** [comment]
Definitely a problem in erasure. During erasure, when trying to reduce the match type before erasing its bound, I observe a weird behavior. It sees as `tycon` of the match case pattern `Test.Named.Named` -- so far so good. But `tycon.info` gives `[name <: String & Singleton,A] = A`. That does not seem correct to me. At erasure, the info should still be the public abstract bounds `>: [name] =>> Tupe <: [name] =>> Any`. Shouldn't it? `ctx.phase` is `erasure` when it computes that.

**Comment by odersky** [comment]
No, opaque type aliases are eliminated before erasure, at phase ElimOpaque.

**Comment by sjrd** [comment]
Oh. Well at least that explains it. It will make this tricky to fix, though. I'll have to think about it more.

**Comment by odersky** [comment]
I just hit this in the wild with some test code using NamedTuples.

**Comment by dwijnand** [comment]
I'm merging ElimOpaque into Erasure
