### ISSUE TITLE
Parameters are not substituted in lambdas in type annotation

### ISSUE THREAD

**Issue by mbovel** [scala/scala3#19846]
## Compiler version

Scala 3.4.2-RC1-bin-20240229-9fe0111-NIGHTLY-git-9fe0111 (17.0.8, Java OpenJDK 64-Bit Server VM)

## Minimized code

Let `dependentAnnotation.scala` contain:

```Scala
package dependentAnnotation

class lambdaAnnot(g: () => Int) extends annotation.StaticAnnotation
def f(x: Int): Int @lambdaAnnot(() => x + 1) = x

@main def main =
  val y: Int = 5
  val z = f(y)
```

## Output

```
scala-cli compile -S 3.nightly -Xprint:typer --server=false dependentAnnotation.scala
```

outputs

```scala
...
val z:
    
      Int @lambdaAnnot(
        {
          def $anonfun(): Int = x.+(1) // Not substituted 😱
          closure($anonfun)
        }
      )
    
    = dependentAnnotation.f(y)
  ()
}
...
```

## Expectation

`x` should be substituted to `y`.

This is the case if the annotation takes an `Int` parameter instead of `() => Int`.

<details>

<summary>Example without a lambda</summary>

```scala
package dependentAnnotation2

class intAnnot(predicate: Int) extends annotation.StaticAnnotation
def f(x: Int): Int @intAnnot(x + 1) = x

@main def main =
  val y: Int = 5
  val z = f(y)
```

```
scala-cli compile -S 3.nightly -Xprint:typer --server=false dependentAnnotation2.scala
```

```scala
...
val z: Int @intAnnot(y.+(1)) = dependentAnnotation2.f(y)
...
```

</details>

**Comment by mbovel** [comment]
Maybe related: #18064.

**Comment by mbovel** [comment]
Also makes the pickler crash for `@qualified` annotations, similarly to #20035:

```scala
class qualified[T](predicate: T => Boolean) extends annotation.StaticAnnotation

class EqualPair(val x: Int, val y: Int @qualified[Int](it => it == x))

@main def main =
  val p = EqualPair(42, 42)
  val y = p.y
  println(42)
```

```
java.lang.AssertionError: assertion failed: unresolved symbols: <span class="ansi-color-yellow">parameter</span> <span class="ansi-color-magenta">x</span> (line 3) #7588 when pickling /tmp/scastie5434625360140563661/src/main/scala/main.scala
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:829)
	at dotty.tools.dotc.transform.Pickler.run$$anonfun$1$$anonfun$1(Pickler.scala:90)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.transform.Pickler.run$$anonfun$1(Pickler.scala:142)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.transform.Pickler.run(Pickler.scala:142)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:327)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:331)
	at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:150)
	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:246)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
```
