### ISSUE TITLE
Exports generate broken code depending on location (scope) of said code

### ISSUE THREAD

**Issue by lbialy** [scala/scala3#20079]
This is related to virtuslab/besom#430.

This issue is really mind-bending: in repro in Besom repo I have this working fine if object exporting these implicit methods is in test scope but failing steadily if it's in main scope. Running `scala-cli test .` in this repro shows the same behavior: `in main` crashes while `in test` and `local` both work. If you do however run tests from metals `in main` and `in test` tests fail but `local` works!

## Compiler version

`3.3.1`

## Minimized code

https://github.com/lbialy/besom-issue-430

## Output
Run `scala-cli test .` in the main folder of this repo and you will get:

```
repro.Suite:
==> X repro.Suite.in main  0.006s java.lang.ClassCastException: class scala.collection.immutable.$colon$colon cannot be cast to class scala.collection.View (scala.collection.immutable.$colon$colon and scala.collection.View are in unnamed module of loader 'app')
    at scala.collection.BuildFrom$$anon$8.fromSpecific(BuildFrom.scala:85)
    at repro.Output$.sequence(output.scala:20)
    at repro.OutputExtensionsFactory$OutputSequenceOps.sequence(output.scala:26)
    at repro.OutputExtensionsFactory$OutputTraverseOps.traverse(output.scala:30)
    at repro.Suite.$init$$$anonfun$1(suite.test.scala:19)
  + in test 0.001s
  + local 0.001s
```

## Expectation

I would expect that `Array("a", "b").toList.traverse(str => ...)` would infer `CC` type param in `traverse` as `List` and not `View`:
<img width="1403" alt="Screenshot 2024-04-03 at 14 34 31" src="https://github.com/scala/scala3/assets/8607442/d17a7c83-d195-42a3-9cb2-783f5abe8de0">

`toList` infers `List[File]`:
<img width="576" alt="Screenshot 2024-04-03 at 11 46 35" src="https://github.com/scala/scala3/assets/8607442/9c873775-d725-4382-a17f-41b241f212d5">
but then `traverse` infers `Output[View[X]]`:
<img width="1108" alt="Screenshot 2024-04-03 at 11 47 00" src="https://github.com/scala/scala3/assets/8607442/fe630d87-a949-47f2-b92d-a923bbdc729d">

**Comment by prolativ** [comment]
Metals are not to blame for anything here: `in test` works after a clean compilation, but it crashes when compiled incrementally with scala-cli (after modifying `suite.test.scala` only). With `--server=false` ``in test`` works too.

**Comment by prolativ** [comment]
In general the crash in runtime seems to be caused by the compiler picking up the wrong instance of  `BuildFrom` (`buildFromView` instead of `buildFromIterableOps`), which is a result of wrong type inference. Note that in the scope of `in main` the compiler doesn't refuse to compile `OutputSequenceOps[Int, scala.collection.View](ints).sequence`, which should be invalid because `ints` is a `List[Int]` and `List[Int]` is not a subtype of `View[Int]`

**Comment by prolativ** [comment]
A minimization as a (currently failing) Vuilpix-style `neg` test:

`Lib_1.scala`:
```scala
object Foo:
  def xyz[A, CC[X] <: Iterable[X]](coll: CC[Option[A]]): Unit = ()

object Bar:
  export Foo.xyz
```

`Test_2.scala`:
```scala
object Test:
  val ints = List(Option(1))
  Foo.xyz[Int, List](ints)
  Foo.xyz[Int, scala.collection.View](ints) // error
  Bar.xyz[Int, List](ints)
  Bar.xyz[Int, scala.collection.View](ints) // error
```
The first error is not reported, although it should. However it is reported if we rename `Test_2.scala` to `Test_1.scala`, making all the sources to be compiled together instead of separately
