### ISSUE TITLE
Strange  Error while emitting error when adding a new member to `Surface`

### ISSUE THREAD

**Issue by OndrejSpanel** [scala/scala3#20072]
## Compiler version

3.3.3
3.4.1
3.5.0-RC1-bin-20240331-cc55381-NIGHTLY

## Minimized code

- Clone https://github.com/OpenGrabeso/light-surface/tree/docstring (note branch docstring)
- Run `test` from sbt

## Output

```
java.util.NoSuchElementException: val rawType$2
        at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:508)
        at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:507)
        at scala.collection.mutable.AnyRefMap.apply(AnyRefMap.scala:207)
        at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder$locals$.load(BCodeSkelBuilder.scala:583)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadTo(BCodeBodyBuilder.scala:440)
```

See https://github.com/OpenGrabeso/light-surface/actions/runs/8525399157/job/23352226318

## Expectation

No error. The code compiles fine when you comment out `override val docString: Option[String] = None,` and there is no reason why it should not compile with it.

This is driving me crazy. I have made many changes to this class before and I never had any issues with it, it is based on https://wvlet.org/airframe/docs/airframe-surface

**Comment by OndrejSpanel** [comment]
Another repro of the same issue, might be a better starting point for possible minification, is branch `docstring-def` in the same repo.

The code compiles fine in the commit before the last one, it crashes as soon as you comment `typeArgs = Seq.empty` as seen in the last comment.

The critical code fragment is:

```
      '{
        new org.opengrabeso.airframe.surface.GenericSurface(
          ${ clsOf(t) },
          //typeArgs = Seq.empty,
          params = Seq.empty,
          docString = ${ doc }
        )
      }
```

It seems you need to provide all arguments to `GenericSurface` in the quoted expression in spite of them having defaults, otherwise the compiler crashes.

_Rant: I have worked with Scala 2 macros before, and while design of Scala 3 macros looks elegant and powerful, the implementation is ridden with so many issues that doing anything with them is very frustrating._

**Comment by OndrejSpanel** [comment]
I am trying to reduce the repro. Creating a small repro from scratch did not work, therefore I remove parts of code from the original repro and gradually reducing its size.

**Comment by OndrejSpanel** [comment]
I can create the error even without using default values. This gives the error:

```scala
      val surface = '{
        val docString = None
        new org.opengrabeso.airframe.surface.Surface(docString)
      }
```

This does not:

```scala
      val surface = '{
        val docString = None
        new org.opengrabeso.airframe.surface.Surface(None)
      }
```

Also no error happens when I replace the `Flags.Lazy` with `Flags.EmptyFlags`. The complete expression which causes the failure is:

```
{
  lazy val __A_X_s_A_000: org.opengrabeso.airframe.surface.Surface = {
    val none: scala.None.type = scala.None
    new org.opengrabeso.airframe.surface.Surface(none)
  }
  Seq(__A_X_s_A_000)
}
```

When I provide the same expression explicitely, no error happens - probably some internal compiler state is different.

When I use `-Xcheck-macros`, I get following assertion:

> [error]    |java.lang.AssertionError: assertion failed: Tree had an unexpected owner for val none
> [error]    |Expected: val __A_X_s_A_000 (org.opengrabeso.airframe.surface.MethodSurfaceTest._$_$_$__A_X_s_A_000)
> [error]    |But was: val macro (org.opengrabeso.airframe.surface.MethodSurfaceTest._$_$macro)

I am not sure what this all means.

**Comment by OndrejSpanel** [comment]
The issue can be fixed by using `changeOwner`:

```scala
ValDef(sym, Some(surfaceOf(tpe, useVarRef = false).asTerm.changeOwner(sym)))
```

**Comment by OndrejSpanel** [comment]
Caused by a bad owner on the macro side, not a compiler issue.
