### ISSUE TITLE
Crash when using Expr.summon with SeqMap

### ISSUE THREAD

**Issue by gzoller** [scala/scala3#20094]
## Compiler version
3.3.1

## Minimized code
Minimized/Runnable Repo: [https://github.com/gzoller/scala3_macro_seqmap](https://github.com/gzoller/scala3_macro_seqmap)

Macro code:
```scala
  inline def makeMapFlavor[T](): T =
    ${ makeMapFlavorImpl[T]()  }

  def makeMapFlavorImpl[T]()(using Quotes)(using Type[T]): Expr[T] = 
    '{
      Map("a"->1, "b"->2, "c"->3).to(${ Expr.summon[Factory[(String, Int), T]].get })
    }
```
Usage:
```scala
  // This one works... Any scala.collection.immutable.Map[] subclass, other than SeqMap
  println("Hello world: " + TheMacro.makeMapFlavor[VectorMap[String,Int]]())

  // This blows up
  println("Hello world: " + TheMacro.makeMapFlavor[SeqMap[String,Int]]())
```

## Output (for SeqMap)
```
[error]  6 |  println("Hello world: " + TheMacro.makeMapFlavor[SeqMap[String,Int]]())
[error]    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.util.NoSuchElementException: None.get
[error]    |  at scala.None$.get(Option.scala:627)
[error]    |  at scala.None$.get(Option.scala:626)
[error]    |  at com.stuff.TheMacro$.makeMapFlavorImpl$$anonfun$1(TheMacro.scala:14)
[error]    |  at com.stuff.TheMacro$.makeMapFlavorImpl$$anonfun$adapted$1(TheMacro.scala:14)
[error]    |  at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:111)
[error]    |  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1566)
[error]    |  at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:136)
[error]    |  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1638)
[error]    |  at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]    |  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1638)
[error]    |  at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1532)
[error]    |  at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:136)
[error]    |  at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:153)
[error]    |  at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:89)
[error]    |  at scala.quoted.runtime.impl.QuotesImpl.unpickleExprV2(QuotesImpl.scala:3211)
[error]    |  at com.stuff.TheMacro$.makeMapFlavorImpl(TheMacro.scala:14)
```

## Expectation
I want to to some type coersion to return any "flavor" of a Map asked by the user (ie Map subclass).  Code in macro should do this, using Expr.summon to get a Factory.  This works for every flavor of Map I tried--except SeqMap.  Not sure what's special about that one, but its the only one I saw that failed.

**Comment by nicolasstucki** [comment]
### Minimized 

```scala
import scala.collection.immutable.SeqMap
import scala.collection.Factory
def test = summon[Factory[(String, Int), SeqMap[String,Int]]]
```

**Comment by nicolasstucki** [comment]
`Expr.summon[Factory[(String, Int), SeqMap[String,Int]]]` is expected to return `None` because of the ambiguous implicit.

If you want to handle that case explicitly use `quotes.reflect.Implicits.search` instead.
