### ISSUE TITLE
Trying to reproduce DottyTest.scala test environment produces classpath issues

### ISSUE THREAD

**Issue by kincsescsaba** [scala/scala3#20182]
## Minimized code

I created a simple demonstration repo which can be found here: [https://github.com/kincsescsaba/dotty-test-classpath-problem](https://github.com/kincsescsaba/dotty-test-classpath-problem)

There are two test scenarios. Please run `Classpath check` to see that Scala compiler related libs which are assumed to be needed are on the classpath. Check out `Scenario1` which produces an error message.

This part of the code produces the error:
```scala
val base = new ContextBase
val context = base.initialCtx.fresh
base.initialize()(using context)
```

## Output

```scala
Could not find package scala from compiler core libraries.
Make sure the compiler core libraries are on the classpath.
   
dotty.tools.dotc.MissingCoreLibraryException: Could not find package scala from compiler core libraries.
Make sure the compiler core libraries are on the classpath.
   
	at dotty.tools.dotc.core.Denotations$.select$1(Denotations.scala:1320)
	at dotty.tools.dotc.core.Denotations$.recurSimple$1(Denotations.scala:1348)
	at dotty.tools.dotc.core.Denotations$.recur$1(Denotations.scala:1350)
	at dotty.tools.dotc.core.Denotations$.staticRef(Denotations.scala:1354)
	at dotty.tools.dotc.core.Symbols$.requiredPackage(Symbols.scala:928)
	at dotty.tools.dotc.core.Definitions.ScalaPackageVal(Definitions.scala:215)
	at dotty.tools.dotc.core.Definitions.ScalaPackageClass(Definitions.scala:218)
	at dotty.tools.dotc.core.Definitions.AnyClass(Definitions.scala:280)
	at dotty.tools.dotc.core.Definitions.syntheticScalaClasses(Definitions.scala:2132)
	at dotty.tools.dotc.core.Definitions.syntheticCoreClasses(Definitions.scala:2147)
	at dotty.tools.dotc.core.Definitions.init(Definitions.scala:2163)
	at dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:900)
	at io.github.kincsescsaba.dottytestclasspathproblem.Repl$.io$github$kincsescsaba$dottytestclasspathproblem$Repl$$$context(Repl.scala:31)
	at io.github.kincsescsaba.dottytestclasspathproblem.Repl.<init>(Repl.scala:18)
	at io.github.kincsescsaba.dottytestclasspathproblem.Repl$.apply(Repl.scala:26)
	at io.github.kincsescsaba.dottytestclasspathproblem.ExampleTest.testFun$proxy2$1(ExampleTest.scala:15)
	at io.github.kincsescsaba.dottytestclasspathproblem.ExampleTest.fun$proxy1$1$$anonfun$2(ExampleTest.scala:14)
...
```

## Expectation
I expected this code to run smoothly without any classpath errors.
I tried to adapt this file: [https://github.com/scala/scala3/blob/main/compiler/test/dotty/tools/DottyTest.scala](https://github.com/scala/scala3/blob/main/compiler/test/dotty/tools/DottyTest.scala)

Please note that I did not use Vulpix, and I don't know how to import it as I did not find it in Maven Central (what's a proper way of adding Vulpix if needed?). Though it should work by any manual classpath configuration.

**Comment by Gedochao** [comment]
> what's a proper way of adding Vulpix if needed?

AFAIK there isn't. Vulpix is an internal framework for testing the compiler, it is not prepared for external use, and it is not being published anywhere.

> I created a simple demonstration repo which can be found here: https://github.com/kincsescsaba/dotty-test-classpath-problem

@kincsescsaba What is it that you were trying to test here? I'm not sure if the `DottyTest.scala`test framework even should be reproducible without Vulpix (but I'm pretty sure it wasn't meant to be).

I do not consider this a bug at this point, I'm just trying to understand the intent of what was attempted here.

**Comment by prolativ** [comment]
It looks like there are just a few small changes needed for this not to crash:
1) To fix `Classpath check`:
* Add `Test / fork := true` inside `.settings(...)` in `build.sbt`
2) To fix `Scenario1`:
* Remove `base.initialize()(using context)`
* Change `Parsers.parser(...)` to `Parsers.Parser(...)`

**Comment by kincsescsaba** [comment]
> I do not consider this a bug at this point, I'm just trying to understand the intent of what was attempted here.

@Gedochao I'm trying to implement a simple test framework to test a compiler plugin, which should fail with an error if security problematic code was entered. I found the implementation idea including a reference to DottyTest.scala, in the below video (see 13:23, 15:14). The demo repo I attached includes the first steps of the implementation.

https://www.youtube.com/watch?v=UpsRLbEHmik

**Comment by kincsescsaba** [comment]
@prolativ Thanks for checking, removing `base.initialize()(using context)` and changing the Parser fixed the issue.

Looks like Vulpix has nothing to do with this, I simply misused the parser, and the initialization process was not clear.

**Comment by kincsescsaba** [comment]
I pushed the fixes, including some clarifications, to the repo, closing this now.
