### ISSUE TITLE
Failure in function literal adaptation to partial function

### ISSUE THREAD

**Issue by som-snytt** [scala/scala3#20197]
## Compiler version

3.4.1

## Minimized code

```Scala
Welcome to Scala 3.4.1 (21.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> List(42).collect((x: Any) => x match { case "42" => 27 })
1 warning found
-- [E030] Match case Unreachable Warning: ------------------------------------------------------------------------------
1 |List(42).collect((x: Any) => x match { case "42" => 27 })
  |                                            ^^^^
  |                                            Unreachable case
java.lang.AbstractMethodError: Receiver class rs$line$1$$anon$1 does not define or inherit an implementation of the resolved method 'abstract boolean isDefinedAt(java.lang.Object)' of interface scala.PartialFunction.
  at scala.PartialFunction.applyOrElse(PartialFunction.scala:214)
  at scala.PartialFunction.applyOrElse$(PartialFunction.scala:213)
  at scala.runtime.AbstractPartialFunction.applyOrElse(AbstractPartialFunction.scala:27)
  at scala.collection.immutable.List.collect(List.scala:267)
  ... 33 elided
```

## Output

It has progressed to warning.

## Expectation

Not an abstract method error.

Noticed at related effort to align with dotty at https://github.com/scala/scala/pull/10486

**Comment by Gedochao** [comment]
```scala
//> using scala 2.13.13
List(42).collect((x: Any) => x match { case "42" => 27 })
```
BTW for 2.13.13 it fails at compile time. 
```bash
scala-cli repro-script.sc   
# Compiling project (Scala 2.13.13, JVM (17))
# [error] ./repro-script.sc:2:45
# [error] type mismatch;
# [error]  found   : String("42")
# [error]  required: Int
# [error] List(42).collect((x: Any) => x match { case "42" => 27 })
# [error]                                             ^
# Error compiling project (Scala 2.13.13, JVM (17))
```
While on Scala 3 (both LTS & Next) we just get a warning and then a failure at runtime.
```bash
scala-cli repro-script.sc -S 3.4.1
# [warn] ./repro-script.sc:2:45
# [warn] Unreachable case
# [warn] List(42).collect((x: Any) => x match { case "42" => 27 })
# [warn]                                             ^^^^
# Exception in thread "main" java.lang.AbstractMethodError: Receiver class repro$minusscript$_$$anon$1 does not define or inherit an implementation of the resolved method 'abstract boolean isDefinedAt(java.lang.Object)' of interface scala.PartialFunction.
#         at scala.PartialFunction.applyOrElse(PartialFunction.scala:214)
#         at scala.PartialFunction.applyOrElse$(PartialFunction.scala:213)
#         at scala.runtime.AbstractPartialFunction.applyOrElse(AbstractPartialFunction.scala:27)
#         at scala.collection.immutable.List.collect(List.scala:267)
#         at repro$minusscript$_.<init>(repro-script.sc:2)
#         at repro$minusscript_sc$.script$lzyINIT1(repro-script.sc:16)
#         at repro$minusscript_sc$.script(repro-script.sc:16)
#         at repro$minusscript_sc$.main(repro-script.sc:20)
#         at repro$minusscript_sc.main(repro-script.sc)
```

**Comment by som-snytt** [comment]
```scala
Welcome to Scala 2.13.18 (OpenJDK 64-Bit Server VM, Java 25.0.2).
Type in expressions for evaluation. Or try :help.

scala> List(42).collect((x: Any) => x match { case "42" => 27 })
val res0: List[Int] = List()
```
This might be that tweak where the parameter type was previously neglected by Scala 2. Works since 2.13.17.
