### ISSUE TITLE
Error message in log when compiling: BufferStrategyPaintManager$ with Java 17+

### ISSUE THREAD

**Issue by OndrejSpanel** [scala/scala3#20438]
## Compiler version

3.4.2

## Minimized code

I do not have a minimized code yet. I appear reproducibly, but only in a large project and only with Java 17 / 21, not with Java 11, and only when there are other errors in the project.

## Output (click arrow to expand)

```
exception caught when loading module class BufferStrategyPaintManager$: java.lang.AssertionError: assertion failed: failure to resolve inner class:eIncremental 3s
externalName = javax.swing.RepaintManager$PaintManager,
outerName = javax.swing.RepaintManager,
innerName = PaintManager
owner.fullName = javax.swing.RepaintManager
while parsing C:\Users\Ondra\.sbt\1.0\java9-rt-ext-eclipse_adoptium_21_0_3\rt.jar(javax/swing/BufferStrategyPaintManager.class)
```

For a full stack see https://gist.github.com/OndrejSpanel/df207819ccc5cfe845356e357f964db4

## Note

Originally reported as https://github.com/sbt/sbt/issues/7561 and https://youtrack.jetbrains.com/issue/SCL-22558

I am willing to take some effort to minimize the repro, but some hint regarding what could be causing the bug would help, so that I can minimize faster.

I am able to attach debugger to sbt, reproduce it and send any more information from the debugger if wanted.

**Comment by OndrejSpanel** [comment]
I have a short scalac repro.

Two files are needed, Java and Scala, and `rt.jar`, which I have copied from _scala-compile-server\jvm-rt\java9-rt-ext-eclipse_adoptium_21_0_3scala-compile-server\jvm-rt\java9-rt-ext-eclipse_adoptium_21_0_3_. Java must be listed first in the command line, it must import `javax.swing` and scalac needs to use `-release 11`. Scala file must contain an error.

The command line for reproduction in the directory of clone of https://github.com/OndrejSpanel/PaintManagerException is:

```
scalac "-Dscala.ext.dirs=." -release 11 .\src\main\scala\File.java .\src\main\scala\Launcher.scala
```

**Comment by OndrejSpanel** [comment]
It seems rt.jar can be reduced to contain just a few classes. I am sure someone can take over now.

**Comment by OndrejSpanel** [comment]
Can someone take a look and decide how serious the issue is and what should be done with it? Creating minimal repro was a substantial effort and I would not like seeing it wasted.

**Comment by Gedochao** [comment]
> Can someone take a look and decide how serious the issue is and what should be done with it? Creating minimal repro was a substantial effort and I would not like seeing it wasted.

@OndrejSpanel I'll make sure someone takes a look soon.

**Comment by OndrejSpanel** [comment]
Is there any more information needed, or any other help I could offer?

**Comment by smarter** [comment]
The error message is triggering the import suggestion mechanism that tries to find any given or extension method that might match in your entire classpath and seems to explode because it's looking at a package-private inner java class. As a work around, you can turn off import suggestions with:
```scala
scalac -Ximport-suggestion-timeout 0
```
or from an sbt build:
```scala
scalacOptions ++= Seq("-Ximport-suggestion-timeout", "0")
```

<hr>

More precisely, the stack trace is:
```scala
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.classfile.ClassfileParser$innerClasses$.classSymbol(ClassfileParser.scala:1288)
        at dotty.tools.dotc.core.classfile.ClassfileParser.classNameToSymbol(ClassfileParser.scala:320)
        at dotty.tools.dotc.core.classfile.ClassfileParser.getClassSymbol(ClassfileParser.scala:1376)
        at dotty.tools.dotc.core.classfile.ClassfileParser$ConstantPool.getClassSymbol(ClassfileParser.scala:1337)
        at dotty.tools.dotc.core.classfile.ClassfileParser$AbstractConstantPool.getSuperClass(ClassfileParser.scala:176)
        at dotty.tools.dotc.core.classfile.ClassfileParser.parseParents$1(ClassfileParser.scala:380)
        at dotty.tools.dotc.core.classfile.ClassfileParser.parseClass(ClassfileParser.scala:395)
        at dotty.tools.dotc.core.classfile.ClassfileParser.$anonfun$1(ClassfileParser.scala:302)
        at dotty.tools.dotc.core.classfile.ClassfileParser.run(ClassfileParser.scala:297)
        at dotty.tools.dotc.core.ClassfileLoader.doComplete(SymbolLoaders.scala:418)
        at dotty.tools.dotc.core.SymbolLoader$$anon$1.doComplete(SymbolLoaders.scala:332)
        at dotty.tools.dotc.core.SymbolLoader.complete(SymbolLoaders.scala:348)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:175)
        at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:190)
        at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:192)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:393)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.flags(SymDenotations.scala:66)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.is(SymDenotations.scala:122)
        at dotty.tools.dotc.typer.ImportSuggestions.lookInside$1(ImportSuggestions.scala:67)
        at dotty.tools.dotc.typer.ImportSuggestions.$anonfun$1(ImportSuggestions.scala:91)
        at dotty.tools.dotc.core.Scopes$Scope.filter(Scopes.scala:103)
        at dotty.tools.dotc.typer.ImportSuggestions.rootsStrictlyIn$1(ImportSuggestions.scala:91)
        at dotty.tools.dotc.typer.ImportSuggestions.rootsIn$1(ImportSuggestions.scala:109)
        at dotty.tools.dotc.typer.ImportSuggestions.rootsStrictlyIn$1$$anonfun$2(ImportSuggestions.scala:101)
        at scala.collection.immutable.List.flatMap(List.scala:294)
        at dotty.tools.dotc.typer.ImportSuggestions.rootsStrictlyIn$1(ImportSuggestions.scala:101)
        at dotty.tools.dotc.typer.ImportSuggestions.rootsIn$1(ImportSuggestions.scala:109)
        at dotty.tools.dotc.typer.ImportSuggestions.rootsStrictlyIn$1$$anonfun$2(ImportSuggestions.scala:101)
        at scala.collection.immutable.List.flatMap(List.scala:294)
        at dotty.tools.dotc.typer.ImportSuggestions.rootsStrictlyIn$1(ImportSuggestions.scala:101)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:120)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.recur$1(ImportSuggestions.scala:131)
        at dotty.tools.dotc.typer.ImportSuggestions.suggestionRoots(ImportSuggestions.scala:134)
        at dotty.tools.dotc.typer.ImportSuggestions.importSuggestions(ImportSuggestions.scala:236)
        at dotty.tools.dotc.typer.ImportSuggestions.importSuggestionAddendum(ImportSuggestions.scala:326)
        at dotty.tools.dotc.typer.ImportSuggestions.importSuggestionAddendum$(ImportSuggestions.scala:22)
        at dotty.tools.dotc.typer.Typer.importSuggestionAddendum(Typer.scala:145)
        at dotty.tools.dotc.typer.TypeAssigner.addendum$1$$anonfun$1(TypeAssigner.scala:182)
        at dotty.tools.dotc.typer.ErrorReporting$Errors.selectErrorAddendum(ErrorReporting.scala:279)
        at dotty.tools.dotc.typer.TypeAssigner.addendum$1(TypeAssigner.scala:182)
        at dotty.tools.dotc.typer.TypeAssigner.$anonfun$1(TypeAssigner.scala:185)
        at dotty.tools.dotc.reporting.NotAMember.msg(messages.scala:383)
        at dotty.tools.dotc.reporting.Message.message$$anonfun$1(Message.scala:372)
        at dotty.tools.dotc.reporting.Message.inMessageContext(Message.scala:368)
        at dotty.tools.dotc.reporting.Message.message(Message.scala:372)
        at dotty.tools.dotc.reporting.MessageRendering.messageAndPos(MessageRendering.scala:252)
        at dotty.tools.dotc.reporting.MessageRendering.messageAndPos$(MessageRendering.scala:20)
        at dotty.tools.dotc.reporting.AbstractReporter.messageAndPos(AbstractReporter.scala:8)
        at dotty.tools.dotc.reporting.ConsoleReporter$AbstractConsoleReporter.doReport(ConsoleReporter.scala:43)
        at dotty.tools.dotc.reporting.ConsoleReporter.doReport(ConsoleReporter.scala:23)
        at dotty.tools.dotc.reporting.Reporter.issueUnconfigured(Reporter.scala:160)
        at dotty.tools.dotc.reporting.Reporter.go$1(Reporter.scala:191)
        at dotty.tools.dotc.reporting.Reporter.issueIfNotSuppressed(Reporter.scala:210)
        at dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:213)
        at dotty.tools.dotc.report$.error(report.scala:69)
        at dotty.tools.dotc.typer.ErrorReporting$.errorType(ErrorReporting.scala:32)
        at dotty.tools.dotc.typer.TypeAssigner.notAMemberErrorType(TypeAssigner.scala:186)
        at dotty.tools.dotc.typer.TypeAssigner.notAMemberErrorType$(TypeAssigner.scala:16)
        at dotty.tools.dotc.typer.Typer.notAMemberErrorType(Typer.scala:145)
        at dotty.tools.dotc.typer.Typer.reportAnError$1(Typer.scala:894)
        at dotty.tools.dotc.typer.Typer.typedSelectWithAdapt(Typer.scala:908)
        at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:993)
        at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:1031)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3455)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3564)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3642)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3646)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3757)
        at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:989)
        at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:1031)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3455)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3564)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3642)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3646)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3757)
        at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:989)
        at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:1031)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3455)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3564)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3642)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3646)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3757)
        at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:1051)
        at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1244)
        at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:434)
        at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:145)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3480)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3565)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3642)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3646)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3757)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1434)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3488)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3565)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3642)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3646)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3757)
        at dotty.tools.dotc.typer.Typer.$anonfun$66(Typer.scala:2899)
        at dotty.tools.dotc.inlines.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:256)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2899)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3462)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3564)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3642)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3646)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3668)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3714)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:3162)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:3468)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3472)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3564)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3642)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3646)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3668)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3714)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:3295)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3514)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3565)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3642)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3646)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3757)
        at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:47)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:507)
        at dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:53)
        at dotty.tools.dotc.typer.TyperPhase.$anonfun$4(TyperPhase.scala:99)
        at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:479)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
        at scala.collection.immutable.List.prependedAll(List.scala:155)
        at scala.collection.immutable.List$.from(List.scala:685)
        at scala.collection.immutable.List$.from(List.scala:682)
        at scala.collection.IterableOps$WithFilter.map(Iterable.scala:900)
        at dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:98)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:343)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:336)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:384)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:396)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:396)
        at dotty.tools.dotc.Run.compileSources(Run.scala:282)
        at dotty.tools.dotc.Run.compile(Run.scala:267)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.dotc.Driver.process(Driver.scala:201)
        at dotty.tools.dotc.Driver.process(Driver.scala:169)
        at dotty.tools.dotc.Driver.process(Driver.scala:181)
        at dotty.tools.dotc.Driver.main(Driver.scala:211)
        at dotty.tools.dotc.Main.main(Main.scala)
```

The import suggestion line that forces the completion of the synthetic companion object `BufferStrategyPaintManager` is:
https://github.com/scala/scala3/blob/8244d67fc0456baee6f477f66571d12e7deb18c5/compiler/src/dotty/tools/dotc/typer/ImportSuggestions.scala#L67 which triggers parsing of BufferStrategyPaintManager.class to check if `JavaDefined` is true. I think we normally manage to parse package-private java classes, but this one extends a package-private inner class which I guess is normally skipped by the parser.
To fix this, I think we need a fast reliably way to determine that a symbol is a Java class without having to actually parse the entire class file which can trigger completion of other Java classes. If we only cared about picking up Scala 3 givens/extensions, we could check if a .tasty file exists, but the suggestion mechanism tries to account for extension methods defined in Scala 2 too, so actually opening the .class file seems necessary. /cc @odersky

**Comment by SethTisue** [comment]
@OndrejSpanel I'm not able to reproduce the problem on MacOS:

```
% java -version 
openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment Temurin-17.0.13+11 (build 17.0.13+11)
OpenJDK 64-Bit Server VM Temurin-17.0.13+11 (build 17.0.13+11, mixed mode, sharing)
% gh repo clone OndrejSpanel/PaintManagerException  
Cloning into 'PaintManagerException'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 23 (delta 1), reused 4 (delta 0), pack-reused 17 (from 1)
Receiving objects: 100% (23/23), 62.02 MiB | 44.19 MiB/s, done.
Resolving deltas: 100% (4/4), done.
% cd PaintManagerException 
build.sbt  project/   rt.jar     src/
% /usr/local/scala/scala3-3.3.3/bin/scalac -Dscala.ext.dirs=. -release 11 ./src/main/scala/File.java ./src/main/scala/Launcher.scala 
-- [E008] Not Found Error: ./src/main/scala/Launcher.scala:3:8 -----------------
3 |    org.scala.intentional.error()
  |    ^^^^^^^^^
  |    value scala is not a member of org - did you mean org.scalajs?
1 error found
```

am I doing something a bit different/wrong? have you observed the problem on any other OS besides Windows?

**Comment by SethTisue** [comment]
I was thinking that even if I can't fix the underlying issues, perhaps I could have the import-suggestion code catch the exception, print a diagnostic of some kind, and carry on.

**Comment by OndrejSpanel** [comment]
> have you observed the problem on any other OS besides Windows?

Locally I use Windows 11 only. I can see it reproduced on Linux of Github runners with Java 21, though. See e.g. https://github.com/OndrejSpanel/PaintManagerException/actions/runs/11513023388/job/32048990087?pr=1:

```text
exception caught when loading module class BufferStrategyPaintManager$: java.lang.AssertionError: assertion failed: failure to resolve inner class:
externalName = javax.swing.RepaintManager$PaintManager,
outerName = javax.swing.RepaintManager,
innerName = PaintManager
owner.fullName = javax.swing.RepaintManager
while parsing /home/runner/.sbt/1.0/java9-rt-ext-eclipse_adoptium_[21](https://github.com/OndrejSpanel/PaintManagerException/actions/runs/11513023388/job/32048990087?pr=1#step:4:22)_0_4/rt.jar(javax/swing/BufferStrategyPaintManager.class)
```

**Comment by OndrejSpanel** [comment]
Note: SBT is not needed to reproduce. See https://github.com/scala/scala3/issues/20438#issuecomment-2124351203. 

That said, GitHub runner running MacOS reproduces the issue with sbt without any issues (pun intended):

https://github.com/OndrejSpanel/PaintManagerException/actions/runs/11513147952/job/32049327004?pr=1
