### ISSUE TITLE
Scaladoc snippet compilation fails to evaluate a macro

### ISSUE THREAD

**Issue by lbialy** [scala/scala3#21279]
## Compiler version
3.3.3

## Minimized code

Quite hard to minimize. Problem shows up in scala-yaml repo and can be reproduced reliably by checking out the repo at commit `5bf61d1`.

```bash
git clone git@github.com:VirtusLab/scala-yaml.git

cd scala-yaml

git fetch --all

git checkout 5bf61d1

sbt core/doc

# or

sbt core/publishLocal
```

## Output

```
[error] -- Error: /home/runner/work/scala-yaml/scala-yaml/docs/_docs/examples.md:34:86 -
[error] 34 |case class Keys(key1: String, key2: Option[String], key3: Option[String]) derives YamlDecoder 
[error]    |                                                                                      ^
[error]    |Failed to evaluate macro.
[error]    |  Caused by class java.lang.ClassNotFoundException: org.virtuslab.yaml.DecoderMacros$
[error]    |    java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error]    |    java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error]    |    dotty.tools.dotc.quoted.Interpreter.loadClass(Interpreter.scala:212)
[error]    |    dotty.tools.dotc.quoted.Interpreter.loadModule(Interpreter.scala:197)
[error]    |    dotty.tools.dotc.quoted.Interpreter.interpretedStaticMethodCall(Interpreter.scala:165)
[error]    |    dotty.tools.dotc.quoted.Interpreter.interpretTree(Interpreter.scala:80)
[error]    |    dotty.tools.dotc.transform.Splicer$SpliceInterpreter.interpretTree(Splicer.scala:258)
[error]    |    dotty.tools.dotc.quoted.Interpreter.interpretTree$$anonfun$2(Interpreter.scala:99)
```

## Expectation
Scaladoc can compile snippets that call macros.

**Comment by lbialy** [comment]
@jchyb

**Comment by prolativ** [comment]
Minimized:

build.sh:
```shell
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

cd "$SCRIPT_DIR"
scala-cli --power doc -S 3.3.3 .
```

YamlDecoder.scala:
```scala
package org.virtuslab.yaml

import scala.quoted.*
import scala.deriving.Mirror

trait YamlDecoder[T]

object YamlDecoder {
  inline def derived[T](using m: Mirror.Of[T]): YamlDecoder[T] = ${
    DecoderMacros.deriveImpl[T]
  }
}

object DecoderMacros {
  def deriveImpl[T: Type](using Quotes): Expr[YamlDecoder[T]] =
    '{ new YamlDecoder[T] {} }
}
```

docs/_docs/examples.md:
````
## Test

```scala sc:compile
import org.virtuslab.yaml.*

case class Keys(key1: String) derives YamlDecoder
```
````

This seems to work fine in scala 3.8.3.
However, for LTS 3.3.7 it's a compiler crash:
```scala
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by scala.runtime.LazyVals$ (file:/Users/mpalka/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7.jar)
WARNING: Please consider reporting this to the maintainers of class scala.runtime.LazyVals$
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
Cyclic macro dependencies in compileFromString-e2a1b20b-4a01-4311-acc8-ec8416334d12.scala.
Compilation stopped since no further progress can be made.

To fix this, place macros in one set of files and their callers in another.

Compile with -Xprint-suspension for information.
Cyclic macro dependencies in compileFromString-65162caf-cbf8-435d-a1dc-1f493c77c7ff.scala.
Compilation stopped since no further progress can be made.

To fix this, place macros in one set of files and their callers in another.

Compile with -Xprint-suspension for information.
[error]  Scaladoc generation failed (exit code: 1)
```

**Comment by prolativ** [comment]
It looks, however, that a small change to the build can make the compiler crash:

build.sh:
```shell
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

scala-cli --power doc -f --server=false -S 3.8.3 "$SCRIPT_DIR" -O -siteroot -O "$SCRIPT_DIR/docs"
```
resulting in
```
bad option '-siteroot' was ignored

  exception occurred while compiling List(/Users/mpalka/Projects/scala3/local/repro/i21279/github2/docs, /Users/mpalka/Projects/scala3/local/repro/i21279/github2/YamlDecoder.scala)

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.


     while compiling: <no file>
        during phase: <some phase>
                mode: Mode(ImplicitsEnabled)
     library version: version 3.8.3
    compiler version: version 3.8.3
            settings: -classpath /Users/mpalka/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.8.3/scala3-library_3-3.8.3.jar:/Users/mpalka/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/3.8.3/scala-library-3.8.3.jar -d /Users/mpalka/Projects/scala3/local/repro/i21279/github2/.scala-build/github2_23d63d677d/classes/main -sourceroot /Users/mpalka/Projects/scala3/local/repro/i21279/github2

Exception in thread "main" java.io.IOException: Is a directory
        at java.base/sun.nio.ch.UnixFileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.UnixFileDispatcherImpl.read(UnixFileDispatcherImpl.java:51)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:341)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:307)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:284)
        at java.base/sun.nio.ch.FileChannelImpl.implRead(FileChannelImpl.java:251)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:231)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:90)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:119)
        at dotty.tools.io.AbstractFile.toByteArray(AbstractFile.scala:179)
        at dotty.tools.dotc.util.SourceFile$.apply(SourceFile.scala:310)
        at dotty.tools.dotc.core.Contexts$.dotty$tools$dotc$core$Contexts$Context$$_$getSource$$anonfun$1(Contexts.scala:259)
        at dotty.tools.dotc.util.HashMap.getOrElseUpdate(HashMap.scala:75)
        at dotty.tools.dotc.core.Contexts$Context.getSource(Contexts.scala:259)
        at dotty.tools.dotc.Run.compile$$anonfun$1(Run.scala:304)
        at scala.collection.immutable.List.map(List.scala:240)
        at dotty.tools.dotc.Run.compile(Run.scala:304)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.dotc.Driver.process(Driver.scala:212)
        at dotty.tools.dotc.Driver.process(Driver.scala:180)
        at dotty.tools.dotc.Driver.process(Driver.scala:192)
        at dotty.tools.dotc.Driver.main(Driver.scala:222)
        at dotty.tools.dotc.Main.main(Main.scala)
-- Error: /Users/mpalka/Projects/scala3/local/repro/i21279/github2/docs/_docs/examples.md:4:15 
4 |import org.virtuslab.yaml.*
  |               ^
  |               value virtuslab is not a member of org
-- Error: /Users/mpalka/Projects/scala3/local/repro/i21279/github2/docs/_docs/examples.md:4:25 
4 |import org.virtuslab.yaml.*
  |                         ^
  |     (<error value virtuslab is not a member of org>#yaml :
  |       <error value virtuslab is not a member of org>) is not a legal path
  |     since it is not a concrete type
-- Error: /Users/mpalka/Projects/scala3/local/repro/i21279/github2/docs/_docs/examples.md:6:42 
6 |case class Keys(key1: String) derives YamlDecoder
  |                                          ^
  |<error value virtuslab is not a member of org>#yaml.YamlDecoder is not a class type
[error]  Scaladoc generation failed (exit code: 1)
```

So the compiler complains about `-siteroot` option as being ignored, but it actually does have some effect. Also, omitting `-O "$SCRIPT_DIR/docs"` results in
```
bad option '-siteroot' was ignored
1 warning found
missing argument for option -siteroot
```

**Comment by prolativ** [comment]
Extracted to a separate issue: https://github.com/scala/scala3/issues/25882
