### ISSUE TITLE
sortWith() in some cases throws "java.lang.IllegalArgumentException: Comparison method violates its general contract!"

### ISSUE THREAD

**Issue by talpra** [scala/scala3#21310]
## Compiler version
3.3.3 LTS  (and 2.13.13)

## Minimized code

Found during testing with 2.13.13, but was able to generate exception using Scastie (_scastie.scala-lang.org_) against all versions.  Below exception is generated using the default "Build Settings" of 3.3.3 LTS.

Exception occurs when List length >=32 and last 4 values contain the longest entry.  Tested locally using JDK 21.

```Scala
List("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","1","2","aab","ac","aac","ax").sortWith(_.length >= _.length)
```

## Output

```scala
java.lang.ExceptionInInitializerError
	at Main$.&lt;clinit&gt;(main.scala:9)
	at Main.main(main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.Run.invokeMain(Run.scala:144)
	at sbt.Run.execute$1(Run.scala:94)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
	at sbt.Run$.executeSuccess(Run.scala:187)
	at sbt.Run.runWithLoader(Run.scala:121)
	at sbt.Run.run(Run.scala:128)
	at com.olegych.scastie.sbtscastie.SbtScastiePlugin$$anon$1.$anonfun$run$1(SbtScastiePlugin.scala:38)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:32)
	at sbt.ScastieTrapExit$App.run(ScastieTrapExit.scala:258)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.base/java.util.TimSort.sort(TimSort.java:254)
	at java.base/java.util.Arrays.sort(Arrays.java:1233)
	at scala.collection.SeqOps.sorted(Seq.scala:728)
	at scala.collection.SeqOps.sorted$(Seq.scala:719)
	at scala.collection.immutable.List.scala$collection$immutable$StrictOptimizedSeqOps$$super$sorted(List.scala:79)
	at scala.collection.immutable.StrictOptimizedSeqOps.sorted(StrictOptimizedSeqOps.scala:78)
	at scala.collection.immutable.StrictOptimizedSeqOps.sorted$(StrictOptimizedSeqOps.scala:78)
	at scala.collection.immutable.List.sorted(List.scala:79)
	at scala.collection.SeqOps.sortWith(Seq.scala:756)
	at scala.collection.SeqOps.sortWith$(Seq.scala:756)
	at scala.collection.AbstractSeq.sortWith(Seq.scala:1190)
	at Playground$.&lt;clinit&gt;(main.scala:5)
```

## Expectation
No exception.

**Comment by som-snytt** [comment]
The Scaladoc says "a predicate that is true if its first argument strictly precedes its second argument in the desired ordering".

Also: "The sort is stable. That is, elements that are equal (lt returns false for both directions of comparison) appear in the same order in the sorted sequence as in the original."

"Strictly" means your function is wrong: `x > y`, not `x >= y`. That is more clear from the note on `lt`: "returns false for both directions of comparison".

https://www.scala-lang.org/api/3.4.2/scala/collection/immutable/List.html#sortWith-fffffa25
