### ISSUE TITLE
java.lang.ExceptionInInitializerError when accessing values in parent scope within App runner

### ISSUE THREAD

**Issue by NPCRUS** [scala/scala3#21502]
## Compiler version

3.5.0

## Minimized code

```Scala
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration.DurationInt
import scala.concurrent.{Await, Future}

object Test extends App {
  val string = "hello"

  Await.result(Future(2).map(_ => string), 15.seconds)
}
```

## Output (click arrow to expand)
<details>

```scala
Exception in thread "main" java.lang.ExceptionInInitializerError
        at Test.main(Test.scala)
Caused by: java.util.concurrent.TimeoutException: Future timed out after [15 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
        at scala.concurrent.Await$.result(package.scala:124)
        at Test$.<clinit>(Test.scala:8)
        ... 1 more
java.lang.NoClassDefFoundError: Could not initialize class Test$
```
</details>

## Additional details:
The issue is at the point where you are trying to use variable from the scope(`string`) in a mapping function for Future
Meanwhile this code runs properly with Scala-cli and no `App` runner:
```Scala
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration.DurationInt
import scala.concurrent.{Await, Future}

val string = "hello"

val result = Await.result(Future(2).map(_ => string), 15.seconds)
println(result)
```

**Comment by som-snytt** [comment]
This is the FAQ not to start threads from a class initializer aka constructor of a top-level object.

Same without App:
```
object Test {

  Await.result(Future(2).map(_ => "hello"), 15.seconds)

  def main(args: Array[String]) = println("done")
}
```
App works on Scala 2 because the code is deferred. That was a great feature we all miss.

**Comment by NPCRUS** [comment]
for future folks, who wasn't able to find documentation: [https://www.scala-lang.org/api/current/scala/App.html](https://www.scala-lang.org/api/current/scala/App.html)
