### ISSUE TITLE
Scaladoc: fails to generate doc for ScAS

### ISSUE THREAD

**Issue by rjolly** [scala/scala3#21662]
## Compiler version

3.5.1

## Minimized code

```
git clone https://github.com/rjolly/scas.git
cd scas
./mill -i -D dottyVersion=3.5.1 scas.docJar
```

## Output

```
Problem parsing projects\scas\scas\src\scas\base\BigInteger.scala:[0..13..2002], documentation may not be generated.
[...]
```

## Expectation

It would be good to at least uncomment `e.printStackTrace()` in dotty/scaladoc/src/dotty/tools/scaladoc/tasty/TastyParser.scala (and put it under a flag eventually), so as to know more about the problem.

**Comment by rjolly** [comment]
area:dooctool

**Comment by Gedochao** [comment]
I'd say we need a minimised example to work on this.

**Comment by rjolly** [comment]
```Scala
trait Monoid[T]:
  extension (a: T)
    def \:[U](b: U) = ???
```
```
Problem parsing scas/src/Monoid.scala:<0..61>, documentation may not be generated.
```

**Comment by rjolly** [comment]
This one fails too:
```Scala
trait C[T]
trait Equiv[T]:
  extension[U: C] (x: U)
    def ><[V](y: V) = ???
```
```
Problem parsing scas/src/Equiv.scala:[0..18..117], documentation may not be generated.
```

**Comment by rjolly** [comment]
I think these are the two sole problems. Other than that, my doc generation will be fine. What would be cool is if parsing problems did not propagate, that is, currently if one class has a problem then all its subclasses too, transitively. This makes it hard to point it.

**Comment by Gedochao** [comment]
Both minimized examples seem to generate correctly for 3.3.0 and then break for 3.3.1+.
The output for 3.3.0:
```bash
scala-cli doc repro.scala -S 3.3.0
# Following generated file paths might not be compatible with Jekyll:
# _empty_/Equiv
# _empty_/C
# If using GitHub Pages consider adding a ".nojekyll" file.
# Wrote Scaladoc to ./scala-doc
```

**Comment by rjolly** [comment]
org.scala-lang#scaladoc_3;3.3.1-RC1-bin-20230202-af95ceb-NIGHTLY : no error
org.scala-lang#scaladoc_3;3.3.1-RC1-bin-20230203-3ef1e73-NIGHTLY : error

in between : introduction of clause interleaving. Cc @Sporarum

**Comment by rjolly** [comment]
The error message:
```
java.lang.AssertionError: assertion failed: croppedUnshuffledMemberInfoParamLists and SymOps.nonExtensionParamLists disagree on whether this clause is a type or term one
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.scaladoc.tasty.ClassLikeSupport.$anonfun$21(ClassLikeSupport.scala:391)
```

**Comment by Sporarum** [comment]
I don't have the time to look into it at the moment I'm afraid, maybe @mbovel or @smarter can have a look ?

**Comment by mbovel** [comment]
This issue is already assigned to Mikołaj, so I'll let him have a look, but I am happy to help if needed 🙂
