### ISSUE TITLE
Better error reporting for box adaptation failures

### ISSUE THREAD

**Issue by Linyxus** [scala/scala3#21675]
## Compiler version

`main`

## Minimized code

```Scala
import language.experimental.captureChecking

import scala.collection.mutable.ListBuffer

class MyContainer:
  private val consumers = ListBuffer.empty[() => Unit]

  private def execute(): Unit =
    for consumer <- consumers do
      consumer()

  // ... which, is equivalent to ...

  private def executeAlt(): Unit =
    consumers.foreach: (f: () => Unit) =>
      f()
```

## Output

```scala
-- [E007] Type Mismatch Error: errmsg.scala:9:8 --------------------------------
 9 |    for consumer <- consumers do
   |        ^
   |Found:    (consumer: () => Unit) ->? Unit
   |Required: (consumer: box () => Unit) -><fluid> Unit
   |
   |Note that () => Unit cannot be box-converted to box () => Unit
   |since at least one of their capture sets contains the root capability `cap`
10 |      consumer()
   |
   | longer explanation available when compiling with `-explain`
-- [E007] Type Mismatch Error: errmsg.scala:15:23 ------------------------------
15 |    consumers.foreach: (f: () => Unit) =>
   |                       ^
   |Found:    (f: () => Unit) ->? Unit
   |Required: (f: box () => Unit) -><fluid> Unit
   |
   |Note that () => Unit cannot be box-converted to box () => Unit
   |since at least one of their capture sets contains the root capability `cap`
16 |      f()
   |
   | longer explanation available when compiling with `-explain`
2 errors found
```

## Expectation

The crux of this error is that `ListBuffer[box () => Unit]` is mutable and therefore the type argument `box () => Unit` is invariant. Reach refinement is impossible, and the attempt to unbox its elements results in a box conversion error.

**Comment by Linyxus** [comment]
I am assuming that we do want to hide boxes *completely* from the user. In other words, boxes are internal constructs, and only for those who really curious about what is under the hood are details of boxes relevant.

The problem then becomes how these boxing errors can be translated to human-readable messages. It feels that the only thing that these boxing errors are really talking about is simply "scope violation". And it seems to be at least two kinds of scope violation issues:
1. Functions returning unnamable capabilities
2. Mutable states containing unnamable capabilities

Note that the second category extends beyond `var` definitions. For instance, this issue falls in this second category as well.

It will be interesting to see whether this two scenarios can be detected, and errors be emitted in a more human-readable manner than the status quo.

**Comment by bracevac** [comment]
This is what we get on the current `main`:

```scala
-- Error: local/i21675.scala:6:46 ----------------------------------------------
6 |  private val consumers = ListBuffer.empty[() => Unit]
  |                                           ^^^^^^^^^^
  |Type variable A of method empty cannot be instantiated to () => Unit since
  |that type captures the root capability `cap`.
  |
  |where:    => refers to the universal root capability
-- Error: local/i21675.scala:9:8 -----------------------------------------------
 9 |    for consumer <- consumers do
   |        ^
   |        reference cap is not included in the allowed capture set {}
   |        of the enclosing class MyContainer
10 |      consumer()
-- Error: local/i21675.scala:15:23 ---------------------------------------------
15 |    consumers.foreach: (f: () => Unit) =>
   |                       ^
   |             reference cap is not included in the allowed capture set {}
   |             of the enclosing class MyContainer
16 |      f()
3 errors found
```

So no boxes are exposed, which is better. But the errors themselves are still not very actionable. 

I also tried playing with this example leading to a crash. It doesn't like a reach capability on `caps.cap`:


```scala
import language.experimental.captureChecking
import scala.collection.mutable.ListBuffer

class MyContainer:
  var consumers = ListBuffer.empty[() ->{caps.cap*} Unit]

  def execute(): Unit =
    for consumer <- consumers do
      consumer()

  // ... which, is equivalent to ...

  def executeAlt(): Unit =
    consumers.foreach: (f: () => Unit) =>
      f()
```

<details>

```
Exception in thread "main" java.lang.UnsupportedOperationException: cap.reach
        at dotty.tools.package$.unsupported(package.scala:9)
        at dotty.tools.dotc.cc.Capabilities$GlobalCap$.reach(Capability.scala:127)
        at dotty.tools.dotc.cc.CaptureOps$package$.toCapability(CaptureOps.scala:80)
        at dotty.tools.dotc.cc.CaptureOps$package$.retainedElements$$anonfun$1(CaptureOps.scala:104)
        at scala.collection.immutable.List.map(List.scala:247)
        at dotty.tools.dotc.cc.CaptureOps$package$.retainedElements(CaptureOps.scala:104)
        at dotty.tools.dotc.cc.CaptureOps$package$.toCaptureSet(CaptureOps.scala:64)
        at dotty.tools.dotc.cc.Setup$toCapturing$2$.innerApply(Setup.scala:456)
        at dotty.tools.dotc.cc.Setup$SetupTypeMap.apply(Setup.scala:210)
        at dotty.tools.dotc.cc.Setup$SetupTypeMap.apply$(Setup.scala:196)
        at dotty.tools.dotc.cc.Setup$toCapturing$2$.apply(Setup.scala:378)
        at dotty.tools.dotc.cc.Setup.transform$1(Setup.scala:483)
        at dotty.tools.dotc.cc.Setup.dotty$tools$dotc$cc$Setup$$transformExplicitType(Setup.scala:489)
        at dotty.tools.dotc.cc.Setup$$anon$3.transformTT(Setup.scala:544)
        at dotty.tools.dotc.cc.Setup$$anon$3.traverse$$anonfun$5(Setup.scala:601)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:905)
        at dotty.tools.dotc.cc.Setup$$anon$3.traverse(Setup.scala:596)
        at dotty.tools.dotc.cc.Setup$$anon$3.traverse(Setup.scala:592)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.recur$2(tpd.scala:1347)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.apply(tpd.scala:1350)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.apply(tpd.scala:1342)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1766)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1808)
        at dotty.tools.dotc.cc.Setup$$anon$3.traverse(Setup.scala:630)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1807)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1807)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1763)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1808)
        at dotty.tools.dotc.cc.Setup$$anon$3.traverse(Setup.scala:608)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.recur$2(tpd.scala:1347)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.apply(tpd.scala:1350)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.apply(tpd.scala:1342)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverse(Trees.scala:1806)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.recur$2(tpd.scala:1345)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.apply(tpd.scala:1350)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.apply(tpd.scala:1342)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverse(Trees.scala:1806)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.recur$2(tpd.scala:1345)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.apply(tpd.scala:1350)
        at dotty.tools.dotc.ast.tpd$TreeTraverserWithPreciseImportContexts.apply(tpd.scala:1342)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1772)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1808)
        at dotty.tools.dotc.cc.Setup$$anon$3.traverse(Setup.scala:630)
        at dotty.tools.dotc.cc.Setup.setupUnit(Setup.scala:940)
        at dotty.tools.dotc.cc.CheckCaptures$CaptureChecker.checkUnit(CheckCaptures.scala:1841)
        at dotty.tools.dotc.transform.Recheck.run(Recheck.scala:147)
        at dotty.tools.dotc.cc.CheckCaptures.run(CheckCaptures.scala:228)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:383)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:334)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:376)
        at dotty.tools.dotc.transform.Recheck.runOn(Recheck.scala:151)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:368)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1324)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:361)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$2(Run.scala:408)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$adapted$1(Run.scala:408)
        at scala.Function0.apply$mcV$sp(Function0.scala:42)
        at dotty.tools.dotc.Run.showProgress(Run.scala:470)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:408)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:420)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:420)
        at dotty.tools.dotc.Run.compileSources(Run.scala:307)
        at dotty.tools.dotc.Run.compile(Run.scala:292)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.dotc.Driver.process(Driver.scala:201)
        at dotty.tools.dotc.Driver.process(Driver.scala:169)
        at dotty.tools.dotc.Driver.process(Driver.scala:181)
        at dotty.tools.dotc.Driver.main(Driver.scala:211)
        at dotty.tools.dotc.Main.main(Main.scala)
```

</details>

**Comment by bracevac** [comment]
Another question about this example is how do we actually instantiate such collections:
```scala
import language.experimental.captureChecking
import caps.*

trait Collection[T] extends Mutable:
  update def add(elem: T): Unit
  update def remove(elem: T): Unit
  def get(index: Int): Option[T]

object Collection:
  def empty[T]: Collection[T] = ???

trait Foo:
  val thunks: Collection[() => Unit] // that's fine

object FooImpl1 extends Foo:
  val thunks: Collection[() => Unit] = Collection.empty // error

```
Looks like a bug?
```scala
-- [E007] Type Mismatch Error: local/i21675.scala:17:39 ------------------------
16 |  val thunks: Collection[() => Unit] = Collection.empty
   |                                       ^^^^^^^^^^^^^^^^
   |Found:    Collection[() ->? Unit]^{cap.rd}
   |Required: Collection[() => Unit]^{cap².rd}
   |
   |where:    cap  is a fresh root capability in the result type of method empty
   |          cap² is a fresh root capability in the type of value thunks
   |
   | longer explanation available when compiling with `-explain`
```

**Comment by bracevac** [comment]
After discussing in the LAMP meeting, the previous example is an instance of interactions with type variables and freshness that we need to iron out.

**Comment by Linyxus** [comment]
Instantiating type variables with a cap does not make sense, unless the cap is interpreted as an existential bound at the class level, somehow. I see here too an interaction between mutable variables and freshness levels.

**Comment by odersky** [comment]
There are several issues at play here;

For explicitly given types in `TypeApply`s we don't convert cap to fresh if the type in question is boxed. here's the relevant code from `Setup`:
```scala
    private def transformTT(tree: TypeTree, sym: Symbol, boxed: Boolean)(using Context): Unit =
      if !tree.hasNuType then
        var transformed =
          if tree.isInferred
          then transformInferredType(tree.tpe)
          else transformExplicitType(tree.tpe, sym, freshen = !boxed, tptToCheck = tree)
        if boxed then transformed = box(transformed)
        tree.setNuType(
          if sym.hasAnnotation(defn.UncheckedCapturesAnnot) then makeUnchecked(transformed)
          else transformed)
```
Note the `freshen = !boxed`.  We don't do the same when we convert types of symbols. 

Because the cap has not been replaced by the fresh, we refuse it as a TypeVar instance. We do allow fresh now, but not cap.

I am not sure this freshen condition is correct. I believe it was added to cause the minimal changes to make the tests pass.

I tried to remove it, replacing with `freshen = true`. Then 13 neg tests fail. 

What we need to do: Remove the condition. Go through the tests. See whether any of them lead to unsoundness. If not and we are convinced the change is correct, update the neg test's scala and check files. I have done a LOT of this lately, would be good if someone else could take this over.

**Comment by odersky** [comment]
The other issue is that we now create a separate fresh each time we see a `^` or `=>`. We should be able to unify these, but it seems there's a reason why that fails. Maybe the RHS has a wrong level? That would be my guess.

**Comment by Linyxus** [comment]
I could try turning them off and see what happens.

I think the freshness level is coming into play here. One thing that seems a bit interesting to me is that for scoped capabilities, the freshness level seems to follow a reversed condition than those for fresh capabilities. For fresh capabilities, a less-nested fresh subsumes a more nested one (since the inner fresh is "more" fresh). But for scoped capabilities, a less-nested (or outer) fresh should not subsume an inner one, since this is a scope extrusion.

**Comment by odersky** [comment]
> I think the freshness level is coming into play here. One thing that seems a bit interesting to me is that for scoped capabilities, the freshness level seems to follow a reversed condition than those for fresh capabilities. For fresh capabilities, a less-nested fresh subsumes a more nested one (since the inner fresh is "more" fresh).

I don't think that's the case here. We do check that outer fresh cannot subsume inner fresh's We can *lift* an inner fresh in a return type to an outer fresh, but there are strings attached (i.e. the return fresh can only hide local vals and consume parameters).

**Comment by odersky** [comment]
> The other issue is that we now create a separate fresh each time we see a ^ or =>. We should be able to unify these, but it seems there's a reason why that fails. Maybe the RHS has a wrong level? That would be my guess.

I figured that one out now: Since the type parameter is invariant, the cap does _not_ get replaced by a fresh in the type
```scala
Collection[() => Unit]
```
Hence the error. The error message
```
-- [E007] Type Mismatch Error: local/i21675.scala:17:39 ------------------------
16 |  val thunks: Collection[() => Unit] = Collection.empty
   |                                       ^^^^^^^^^^^^^^^^
   |Found:    Collection[() ->? Unit]^{cap.rd}
   |Required: Collection[() => Unit]^{cap².rd}
   |
   |where:    cap  is a fresh root capability in the result type of method empty
   |          cap² is a fresh root capability in the type of value thunks
   |
   | longer explanation available when compiling with `-explain
```
is misleading here. The problem is not the two caps but the element type of collection, where `() ->? Unit` does not unify with `() => Unit`, because `cap` is essentially separate from everything now.

I am not sure what to do about it. Should we replace cap with fresh in more situations? How to make sure this does not impact soundness? We need to come up with a theory and implementation. I need the team to work on this, I can't do it alone.

**Comment by Linyxus** [comment]
I think we should replace all `ResultCap`s with `Fresh`s in the result of an application, regardless of the variance. Since what the signature actually says is:
```
empty: exists c. Collection[() ->{c} Unit]
```
This `c` can be unpacked into a fresh `Fresh` no matter what the variance is.

**Comment by odersky** [comment]
I think that's worth a try, yes. It would mean we also replace caps in argument position, which normally would be replaced later. But maybe that's OK.

**Comment by Linyxus** [comment]
Those will be caps at double-flip occurrences, then. Feels that it should be fine.

**Comment by odersky** [comment]
Ah yes, since simple argument caps are not result caps, so they won't be replaced.

**Comment by bracevac** [comment]
> Another question about this example is how do we actually instantiate such collections:
> 
> import language.experimental.captureChecking
> import caps.*
> 
> trait Collection[T] extends Mutable:
>   update def add(elem: T): Unit
>   update def remove(elem: T): Unit
>   def get(index: Int): Option[T]
> 
> object Collection:
>   def empty[T]: Collection[T] = ???
> 
> trait Foo:
>   val thunks: Collection[() => Unit] // that's fine
> 
> object FooImpl1 extends Foo:
>   val thunks: Collection[() => Unit] = Collection.empty // error
> Looks like a bug?
> 
> -- [E007] Type Mismatch Error: local/i21675.scala:17:39 ------------------------
> 16 |  val thunks: Collection[() => Unit] = Collection.empty
>    |                                       ^^^^^^^^^^^^^^^^
>    |Found:    Collection[() ->? Unit]^{cap.rd}
>    |Required: Collection[() => Unit]^{cap².rd}
>    |
>    |where:    cap  is a fresh root capability in the result type of method empty
>    |          cap² is a fresh root capability in the type of value thunks
>    |
>    | longer explanation available when compiling with `-explain`

This compiles in 3.8.x nightly!

**Comment by bracevac** [comment]
@Linyxus what's the state?
