### ISSUE TITLE
-Yexplicit-nulls result in NPE when calling methods of Any

### ISSUE THREAD

**Issue by theosotr** [scala/scala3#21701]
## Compiler version

3.5.1

## Minimized code

```Scala
@main def foo() = {
  val x: Int | Null = null
  val y: String = x.toString
}
```

## Output

Compiling with `-Yexplicit-nulls` results in a NPE at runtime

```scala
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "x" is null
	at test$package$.foo(test.scala:3)
	at foo.main(test.scala:1)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at dotty.tools.runner.RichClassLoader$.run$extension$$anonfun$1(ScalaClassLoader.scala:36)
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
	at dotty.tools.runner.RichClassLoader$.dotty$tools$runner$RichClassLoader$$$asContext$extension(ScalaClassLoader.scala:18)
	at dotty.tools.runner.RichClassLoader$.run$extension(ScalaClassLoader.scala:36)
	at dotty.tools.runner.CommonRunner.run(ObjectRunner.scala:23)
	at dotty.tools.runner.CommonRunner.run$(ObjectRunner.scala:13)
	at dotty.tools.runner.ObjectRunner$.run(ObjectRunner.scala:48)
	at dotty.tools.runner.CommonRunner.runAndCatch(ObjectRunner.scala:30)
	at dotty.tools.runner.CommonRunner.runAndCatch$(ObjectRunner.scala:13)
	at dotty.tools.runner.ObjectRunner$.runAndCatch(ObjectRunner.scala:48)
	at dotty.tools.MainGenericRunner$.run$1(MainGenericRunner.scala:215)
	at dotty.tools.MainGenericRunner$.process(MainGenericRunner.scala:270)
	at dotty.tools.MainGenericRunner$.main(MainGenericRunner.scala:281)
	at dotty.tools.MainGenericRunner.main(MainGenericRunner.scala)
```

## Expectation

The code should have been rejected.

**Comment by sjrd** [comment]
It is intended for methods of `Any` to throw if the value is `null`. Otherwise we can't have `Null <: Any`, and the entire type system goes out the window because `T <: Any` is the very definition of "`T` is a proper type".

**Comment by theosotr** [comment]
Thanks for the clarification; makes sense. I was confused by the fact that some methods (e.g., `==`) have been disabled for values of Null type.

**Comment by noti0na1** [comment]
> I was just confused by the fact that some methods (e.g., `==`) have been disabled for values of Null type when the receiver is not Null.

`==` has been treated specially. `null` can only be compared with nullable values.

There was some debate whether we should relax this restriction or not: #19258.
