### ISSUE TITLE
Compiler crash when using StringContext and sttp import

### ISSUE THREAD

**Issue by felix-hedenstrom** [scala/scala3#21798]
## Compiler version
3.5.1

## Minimized code

```Scala
//> using scala 3.5.1
//> using dep "com.softwaremill.sttp.client4::core:4.0.0-M19"
import sttp.client4.basicRequest

val bar = uri"bar"
```

## Output (click arrow to expand)
<details>

```scala
exception occurred while typechecking /home/felix/Documents/reproduce/.scala-build/reproduce_bde03bda35-7818e4ce37/src_generated/main/UriBug.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.

     while compiling: /home/felix/Documents/reproduce/.scala-build/reproduce_bde03bda35-7818e4ce37/src_generated/main/UriBug.scala
        during phase: typer
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.14
    compiler version: version 3.5.1
            settings: -bootclasspath /home/felix/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.5.1/scala3-library_3-3.5.1.jar:/home/felix/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.14/scala-library-2.13.14.jar -classpath /home/felix/Documents/reproduce/.scala-build/.bloop/reproduce_bde03bda35-7818e4ce37/bloop-internal-classes/main-HUiwHVF3TrGEOj5VjwiNww==:/home/felix/Documents/reproduce/.scala-build/.bloop/reproduce_bde03bda35-7818e4ce37/bloop-internal-classes/main-FlxZ_dfnS3CAygMbbaacZw==:/home/felix/.cache/coursier/v1/https/repo1.maven.org/maven2/com/softwaremill/sttp/client4/core_3/4.0.0-M19/core_3-4.0.0-M19.jar:/home/felix/.cache/coursier/v1/https/repo1.maven.org/maven2/com/softwaremill/sttp/model/core_3/1.7.11/core_3-1.7.11.jar:/home/felix/.cache/coursier/v1/https/repo1.maven.org/maven2/com/softwaremill/sttp/shared/core_3/1.3.22/core_3-1.3.22.jar:/home/felix/.cache/coursier/v1/https/repo1.maven.org/maven2/com/softwaremill/sttp/shared/ws_3/1.3.22/ws_3-1.3.22.jar -d /home/felix/Documents/reproduce/.scala-build/.bloop/reproduce_bde03bda35-7818e4ce37/bloop-internal-classes/main-HUiwHVF3TrGEOj5VjwiNww== -sourceroot /home/felix/Documents/reproduce

Error compiling project (Scala 3.5.1, JVM (17))
Error: Unexpected error when compiling reproduce_bde03bda35-7818e4ce37: java.lang.UnsupportedOperationException: empty.reduceLeft
	at scala.collection.IterableOnceOps.reduceLeft(IterableOnce.scala:853)
	at scala.collection.IterableOnceOps.reduceLeft$(IterableOnce.scala:851)
	at scala.collection.AbstractIterable.reduceLeft(Iterable.scala:935)
	at dotty.tools.dotc.typer.Applications.widenPrefix$1(Applications.scala:1945)
```
</details>

**Comment by felix-hedenstrom** [comment]
Looks like this is a duplicate of https://github.com/scala/scala3/issues/21669.
