### ISSUE TITLE
-Wsafe-init doesn't detect initialization order problems

### ISSUE THREAD

**Issue by kubukoz** [scala/scala3#22152]
## Compiler version

3.6.1, 3.6.4-RC1-bin-20241204-a67dbb0-NIGHTLY

## Minimized code

```Scala
case class Record(region: String, env: String)

object foo {

  val record = Record(region, env)

  val region = "oops"
  val env = "hello"

}

object Demo extends App { println(foo.record) }
```

compiled with `-Wsafe-init`

## Output

```scala
Record(null,null)
```

## Expectation

something similar to 2.13's behavior under `-Xcheckinit`:

```
scala-cli run . --scala 2.13 -Xcheckinit                                                                                                                                                   
Compiling project (Scala 2.13.15, JVM (21))
[warn] ./demo.scala:5:23
[warn] Reference to uninitialized value region
[warn]   val record = Record(region, env)
[warn]                       ^^^^^^
[warn] ./demo.scala:5:31
[warn] Reference to uninitialized value env
[warn]   val record = Record(region, env)
[warn]                               ^^^
Compiled project (Scala 2.13.15, JVM (21))
Exception in thread "main" java.lang.ExceptionInInitializerError
        at Demo$.delayedEndpoint$Demo$1(demo.scala:12)
        at Demo$delayedInit$body.apply(demo.scala:12)
        at scala.Function0.apply$mcV$sp(Function0.scala:42)
        at scala.Function0.apply$mcV$sp$(Function0.scala:42)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:98)
        at scala.App.$anonfun$main$1$adapted(App.scala:98)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
        at scala.App.main(App.scala:98)
        at scala.App.main$(App.scala:96)
        at Demo$.main(demo.scala:12)
        at Demo.main(demo.scala)
Caused by: scala.UninitializedFieldError: Uninitialized field: demo.scala: 7
        at foo$.region(demo.scala:7)
        at foo$.<clinit>(demo.scala:5)
        ... 14 more
```

**Comment by kubukoz** [comment]
apparently, even without `-Xcheckinit` you get a warning during compilation - I suppose that's more in line with what `-Wsafe-init` should do

**Comment by olhotak** [comment]
`-Wsafe-init` works only for classes, not global objects.

`-Ysafe-init-global` is for global objects, but it is still experimental and under development.

**Comment by kubukoz** [comment]
Good to know! I like the rendering of the trace, very cool :)

Shall we keep this open or is there another ticket that covers `-Ysafe-init-global`?

**Comment by Gedochao** [comment]
> Shall we keep this open or is there another ticket that covers -Ysafe-init-global?

@kubukoz let's keep it, I don't think we track this anywhere else at this point.
I guess it's more of a feature request than a bug per se, too.
