### ISSUE TITLE
It is possible to summon an invalid refined mirror

### ISSUE THREAD

**Issue by kubukoz** [scala/scala3#22161]
## Compiler version

3.5.2, 3.6.4-RC1-bin-20241205-c61897d-NIGHTLY

## Minimized code

```Scala
import scala.deriving.Mirror

@main def demo = {
  val m = summon[Mirror.ProductOf[EmptyTuple] { type MirroredElemTypes = Tuple1[String] }]

  Tuple.fromProductTyped(EmptyTuple)(
    using m
  ): Tuple1[String]
}
```

## Output

```scala
Exception in thread "main" java.lang.ClassCastException: class scala.Tuple$package$EmptyTuple$ cannot be cast to class scala.Tuple1 (scala.Tuple$package$EmptyTuple$ and scala.Tuple1 are in unnamed module of loader 'app')
        at main$package$.demo(main.scala:7)
        at demo.main(main.scala:3)
```

## Expectation

The code shouldn't compile, in the line doing the summon.

**Comment by eejbyfeldt** [comment]
On nightly this produces:
```
$ scala-cli -S 3.nightly
Welcome to Scala 3.9.0-RC1-bin-20260518-0ce4c47-NIGHTLY-git-0ce4c47 (21.0.10, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                    
scala> import scala.deriving.Mirror
       
       @main def demo = {
         val m = summon[Mirror.ProductOf[EmptyTuple] { type MirroredElemTypes = Tuple1[String] }]
       
         Tuple.fromProductTyped(EmptyTuple)(
           using m
         ): Tuple1[String]
       }
-- Error: ----------------------------------------------------------------------
4 |  val m = summon[Mirror.ProductOf[EmptyTuple] { type MirroredElemTypes = Tuple1[String] }]
  |                                                                                          ^
  |MirroredElemTypes mismatch, expected: EmptyTuple.type, found:  = Tuple1[String].
1 error found
```

Probably got fixed by https://github.com/scala/scala3/pull/24080
