### ISSUE TITLE
ClassCastException: class cannot be cast to class scala.runtime.Nothing$

### ISSUE THREAD

**Issue by jtjeferreira** [scala/scala3#22204]
## Compiler version

Scala 3.6.2, 3.5.2, 3.3.4

## Minimized code

```Scala
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.node.{
  JsonNodeFactory,
  ObjectNode,
  TextNode
}

val json: ObjectNode = JsonNodeFactory.instance.objectNode()

def foo(a: String): Unit = {
  a match {
    case "a" =>
      json.set("type", TextNode.valueOf("value"))
    case _ =>
      json.set("type", TextNode.valueOf("value"))

  }
}
foo("")
```

method `set` is a java method:

```java
public <T extends JsonNode> T set(String propertyName, JsonNode value)
```

https://scastie.scala-lang.org/i507EyzXTdO1BM362YaOhA

## Output

```scala
Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class scala.runtime.Nothing$
```

## Expectation

That it does not crash like in scala2 https://scastie.scala-lang.org/gvqImCf7QeKBXahfClCZHA

**Comment by Gedochao** [comment]
Scala CLI repro:
```scala
//> using dep com.fasterxml.jackson.module::jackson-module-scala:2.15.4
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.node.{
  JsonNodeFactory,
  ObjectNode,
  TextNode
}

val json: ObjectNode = JsonNodeFactory.instance.objectNode()

def foo(a: String): Unit = {
  a match {
    case "a" =>
      json.set("type", TextNode.valueOf("value"))
    case _ =>
      json.set("type", TextNode.valueOf("value"))

  }
}
@main def main = foo("")
```

Fails at runtime with:
```scala
Exception in thread "main" java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class scala.runtime.Nothing$ (com.fasterxml.jackson.databind.node.ObjectNode and scala.runtime.Nothing$ are in unnamed module of loader 'app')
        at repro$package$.foo(repro.scala:16)
        at repro$package$.main(repro.scala:20)
        at main.main(repro.scala:20)
```

**Comment by Gedochao** [comment]
cc @sjrd

**Comment by He-Pin** [comment]
seems like the return type is convert to nothing instead insert a  ()

**Comment by He-Pin** [comment]
a quic fix :
```scala
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.node.{
  JsonNodeFactory,
  ObjectNode,
  TextNode
}

val json: ObjectNode = JsonNodeFactory.instance.objectNode()

def foo(a: String): Unit = {
  a match {
    case "a" =>
      json.set("type", TextNode.valueOf("value"))
    case _ =>
      json.set("type", TextNode.valueOf("value"))
      ()
  }
}
foo("")
```

This is a bug I think even I insert the `()` at the end of the method block will not work.

**Comment by sjrd** [comment]
The signature of `set` makes no sense. It is not possible for such a method to return a valid `T` for all `T` extending `JsonNode`. The Scala compiler chooses to instantiate `T = Nothing`, and as expected, `set` is not able to fulfill its promise, so you get a CCE.

There's no language bug, here.

Explicitly write the type parameter to something that `set` actually returns. Presumably `set[JsonNode](...)`.

**Comment by He-Pin** [comment]
That's seems true 
```java
abstract class BaseJsonNode
    extends JsonNode
abstract class ContainerNode<T extends ContainerNode<T>>
    extends BaseJsonNode
class ObjectNode
    extends ContainerNode<ObjectNode>
```

and In `ObjectNode`:
```java
    public <T extends JsonNode> T set(String propertyName, JsonNode value)
    {
        if (value == null) {
            value = nullNode();
        }
        _children.put(propertyName, value);
        return (T) this;
    }
```

I think the code should be written to :
```java
    public ObjectNode set(String propertyName, JsonNode value)
    {
        if (value == null) {
            value = nullNode();
        }
        _children.put(propertyName, value);
        return (T) this;
    }
```

@pjfanning cc

**Comment by He-Pin** [comment]
The current implementation in Jackson will cause error anyway, eg:
```java
ArrayNode arrayNode = objectNode.set(..)
```
which will throw ClassCustException too, but the compiler will not complain.

**Comment by pjfanning** [comment]
If anyone is suggesting that it is Jackson that gets changed, I honestly don't think the Jackson team (which includes me) will be changing the Java code in Jackson to suit the Scala 3 compiler.

Scala 3 users form a tiny minority of Jackson users and it's hard to justify discommoding other Jackson users by changing Jackson APIs.

Jackson 3 might be a place where we can make a change but there is no date for a GA release of Jackson 3.

**Comment by pjfanning** [comment]
Interestingly, Jackson 3 code has been changed so that ObjectNode.set and setAll returns ObjectNode explicitly.

https://github.com/FasterXML/jackson-databind/blob/9b93072efe469d7bb9c3281e90a022f4e83d4443/src/main/java/tools/jackson/databind/node/ObjectNode.java#L537

There are snapshots published.
Note the s01.oss.sonatype.org and the groupId has changed to `tools.jackson` (and the package names too).

https://s01.oss.sonatype.org/content/repositories/snapshots/tools/jackson/core/jackson-databind/3.0.0-SNAPSHOT/

**Comment by sjrd** [comment]
> @jtjeferreira a messy workaround might be feasible. Maybe a Java class in your code base called something like ObjectNodeWrapper that wraps an ObjectNode and that adds set and setAll methods that delegate to the ObjectNode methods. The ObjectNodeWrapper methods would return ObjectNode explicitly.

The correct workaround is much simpler. I mentioned it above: call `set` with an explicit type argument.

**Comment by jtjeferreira** [comment]
> The correct workaround is much simpler. I mentioned it above: call `set` with an explicit type argument.

yes this workaround works and thats what I am using. I just wanted this to work as in scala2... If that not feasible, feel free to close the issue.

**Comment by prolativ** [comment]
Minimization without library dependencies:

Node.java:
```java
public class Node {
    public static <T> T set() {
        return (T) new Node();
    }
}
```

repro.scala:
```scala
object Repro {
  def main(args: Array[String]): Unit =
    args.length match {
      case 0 => Node.set()
      case _ => Node.set()
    }
}
```
No cast exception in scala 2.13.14
