### ISSUE TITLE
`Array.ofDim[Unit](0)` throws `IllegalArgumentException` on Scala.js

### ISSUE THREAD

**Issue by armanbilge** [scala/scala3#22226]
## Compiler version

`3.6.4-RC1-bin-20241216-7dc5008-NIGHTLY`

## Minimized code

```Scala
//> using scala 3.6.4-RC1-bin-20241216-7dc5008-NIGHTLY
//> using platform js

@main def main = Array.ofDim[Unit](0)
```

## Output

```
/tmp/main12667871020961532039.js:1141
      throw e;
      ^

java.lang.IllegalArgumentException
    at $TypeData.newArray (/tmp/main12667871020961532039.js:851:11)
    at $p_jl_reflect_Array$__rec$1__jl_Class__I__AI__O (/tmp/main12667871020961532039.js:1085:39)
    at $c_jl_reflect_Array$.newInstance__jl_Class__AI__O (/tmp/main12667871020961532039.js:1121:10)
    at $c_Lbug$package$.main__Ajl_Void (/tmp/main12667871020961532039.js:982:52)
    at $s_Lmain__main__AT__V (/tmp/main12667871020961532039.js:1135:24)
    at Object.<anonymous> (/tmp/main12667871020961532039.js:2184:1)
    at Object.<anonymous> (/tmp/main12667871020961532039.js:2185:4)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32) {
  jl_Throwable__f_s: null
}
```

## Expectation

On the JVM it returns an array of `scala.runtime.BoxedUnit`.

Follow-up to https://github.com/scala-js/scala-js/issues/5084.

**Comment by SethTisue** [comment]
“Doeraene reward check” when? https://en.wikipedia.org/wiki/Knuth_reward_check

**Comment by sjrd** [comment]
Thanks for the report.

It turns out it's also broken for `new Array[Unit](0)`, and also `Array.ofDim[Unit](0, 0)`.

In general this is because the `ArrayConstructors` phase uses `classOf[Unit]` as element type when calling `newArray`, but it's supposed to use `classOf[BoxedUnit]`.

The JVM is not affected because it doesn't care about this first argument. The JVM backend rewrites calls to `newArray` in a way that doesn't use it.
