### ISSUE TITLE
VerifyError with weird circular reference in class def

### ISSUE THREAD

**Issue by som-snytt** [scala/scala3#9270]
## Minimized code

```Scala
class C:
  object Foo extends Foo.Bar.Base:
    object Bar:
      class Base

@main def test() =
  val c = new C
  val x = new c.Foo.Bar.Base
```

## Output

```scala
$ dotc -d /tmp nested.scala && dotr -classpath /tmp test
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    C$Foo$.<init>(LC;)V @19: invokevirtual
  Reason:
    Type uninitializedThis (current frame, stack[1]) is not assignable to 'C$Foo$'
  Current Frame:
    bci: @19
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'C' }
    stack: { uninitializedThis, uninitializedThis }
  Bytecode:
    0000000: 2bc7 000b bb00 1959 b700 1cbf 2a2b b500
    0000010: 1e2a 2ab6 0022 b700 25b1
  Stackmap Table:
    same_frame(@12)

        at C.Foo(nested.scala:2)
        at nested$package$.test(nested.scala:8)
        at test.main(nested.scala:6)
```

## Expectation

Anything besides a `VerifyError`.

**Comment by odersky** [comment]
This is still an issue in 2021.

**Comment by xerial** [comment]
I also observed a similar compilation error.

**Comment by SolalPirelli** [comment]
I think the VerifyError is a logical consequence of what `-Vprint:all` shows:

```
  final module class C$Foo extends <empty>.C$Foo$Bar.C$Foo$Bar$Base {
    def <init>($outer: C): Unit =
      {
        if $outer eq null then throw new NullPointerException() else ()
        <empty>.C$Foo.$outer = $outer
        super(this.Bar())
        ()
      }
    // ...
  }
```

We can't invoke `this.Bar()` before calling `super()` since `this` is not initialized at this point.

**Comment by SolalPirelli** [comment]
I'll remove area:backend because as @SethTisue pointed out this should be rejected much earlier. The backend can't really do anything at this point, and I don't think we want it to "protect" itself against any random nonsense the frontend could throw at it.
