### ISSUE TITLE
Missing span with unordered named params and varargs (causes crash with semantic db)

### ISSUE THREAD

**Issue by jodersky** [scala/scala3#9824]
## Minimized code

Compiling the following with the `-Ysemanticdb` flag enabled, causes an assertion error to be thrown by [ExtractSemanticDB#localIdx](https://github.com/lampepfl/dotty/blob/de273a26bed82b04e8342f255339126f69ca2440/compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala#L349).
```Scala
// -Ysemanticdb
class Wrapper {

  def fct(p1: Int, p2: Int, extra: Int*): Int = ???

  fct(0, 0) // OK
  fct(p1 = 0, 0) // OK
  fct(0, p2 = 0) // OK
  fct(p1 = 0, p2 = 0) // OK
  fct(p2 = 0, p1 = 0) // java.lang.AssertionError: assertion failed: val extra$1 should have a span
}
```

## Output (click arrow to expand)
<details>

```
exception occurred while compiling main.scala
java.lang.AssertionError: assertion failed: val extra$1 should have a span while compiling main.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: val extra$1 should have a span
        at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.localIdx$1(ExtractSemanticDB.scala:349)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.addSymName(ExtractSemanticDB.scala:370)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.symbolName(ExtractSemanticDB.scala:377)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:151)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1385)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1387)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1420)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1511)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:241)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse$$anonfun$11(ExtractSemanticDB.scala:197)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:197)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1510)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1479)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1511)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:182)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse$$anonfun$1(ExtractSemanticDB.scala:140)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:140)
        at dotty.tools.dotc.semanticdb.ExtractSemanticDB.run(ExtractSemanticDB.scala:47)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:296)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:297)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:180)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:190)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:198)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:205)
        at dotty.tools.dotc.Run.compileSources(Run.scala:142)
        at dotty.tools.dotc.Run.compile(Run.scala:124)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:38)
        at dotty.tools.dotc.Driver.process(Driver.scala:195)
        at dotty.tools.dotc.Driver.process(Driver.scala:164)
        at dotty.tools.dotc.Driver.process(Driver.scala:176)
        at dotty.tools.dotc.Driver.main(Driver.scala:203)
        at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

## Note

This bug prevents metals from working correctly in the project that has the above code. I tried simply removing the assert in question from ExtractSemanticDB (and default to zero), and metals worked again. I'm not sure what is causing the missing span, but I do wonder if semantic DB should fail more gracefully here. Maybe a warning would be enough?

**Comment by jodersky** [comment]
Note that this bug also occurs with default parameters. E.g.

```
def fct(p1: Int, p2: Int = 0, p3: Int = 0, extra: Int*): Int = ???
fct(0, p3 = 0) // causes the same assertion error
```
